(()=>{if(window.__EB_NET18)return;window.__EB_NET18=1;const s=window.__ebSocket;$=x=>document.getElementById(x);const n=v=>Number.isFinite(+v)?+v:0;let source=false,lastRadioKey='',lastTime=-1,lastCinSig='',nickModal=null;
const rm=()=>['ebPing','ebPing15','ebPing16','ebPing17'].forEach(id=>document.getElementById(id)?.remove());
function css(e,x){if(e)e.style.cssText=x}
function hud(){rm();let p=$('ebPing18');if(!p){p=document.createElement('div');p.id='ebPing18';css(p,'position:fixed;top:7px;right:7px;z-index:2147483647;background:#07101bf0;border:1px solid #fff;border-radius:7px;padding:3px 6px;font:bold 10px Arial;min-width:43px;text-align:center;pointer-events:none');document.body.appendChild(p)}let c=$('ebConn18');if(!c){c=document.createElement('div');c.id='ebConn18';css(c,'position:fixed;top:39px;right:7px;z-index:2147483647;background:#07101bf0;color:#fff;border:1px solid #40c9ff;border-radius:7px;font:bold 10px Arial;min-width:105px;max-width:220px;overflow:hidden');c.innerHTML='<div id="ebConnHead18" style="padding:5px 7px;cursor:pointer">Conectados: <span id="ebConnNum18">0</span></div><div id="ebConnList18" style="display:none;max-height:30vh;overflow:auto;border-top:1px solid #293040"><div style="position:sticky;top:0;background:#07101b;padding:3px 5px;text-align:right"><button id="ebName18" type="button" style="width:24px;height:21px;border:1px solid #7280ff;border-radius:5px;background:#202942;color:#fff;font-size:11px">✏️</button></div><div id="ebConnRows18"></div></div>';document.body.appendChild(c);$('ebConnHead18').onclick=()=>{const x=$('ebConnList18');x.style.display=x.style.display==='none'?'block':'none'};$('ebName18').onclick=()=>openName()}
let h=$('ebChat18');if(!h){h=document.createElement('div');h.id='ebChat18';css(h,'position:fixed;left:50%;bottom:7px;transform:translateX(-50%);z-index:2147483647;width:min(205px,58vw);font:10px Arial;color:#fff');h.innerHTML='<div style="display:flex;align-items:center;gap:3px;background:#07101be8;border:1px solid #40c9ff;border-radius:11px;padding:2px 3px"><button id="ebChatA18" type="button" style="width:21px;height:21px;border:0;border-radius:50%;background:#202942;color:#fff;font-size:11px">↑</button><div id="ebChatLast18" style="flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#ddd">Chat</div><button id="ebChatSend18" type="button" style="width:24px;height:21px;border:0;border-radius:6px;background:#202942;color:#fff;font-size:10px">➤</button></div><div id="ebChatP18" style="display:none;margin-bottom:3px;background:#07101bf5;border:1px solid #40c9ff;border-radius:7px;overflow:hidden"><div id="ebChatM18" style="height:95px;overflow:auto;padding:4px;font-size:9px"></div><div style="display:flex;gap:2px;padding:3px;border-top:1px solid #293040"><input id="ebChatI18" maxlength="120" placeholder="Mensaje..." style="flex:1;min-width:0;border:1px solid #59657a;border-radius:4px;background:#111927;color:#fff;padding:4px;font-size:9px"><button id="ebChatGo18" type="button" style="border:1px solid #40c9ff;border-radius:4px;background:#202942;color:#fff;padding:0 6px;font-size:9px">Enviar</button></div></div>';document.body.appendChild(h);$('ebChatA18').onclick=()=>toggleChat();$('ebChatSend18').onclick=()=>focusChat();$('ebChatGo18').onclick=()=>sendChat();$('ebChatI18').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendChat();hideKeyboard()}}}
}
function pingColor(v){return v<=45?'#b8ffb8':v<=80?'#72ff72':v<=130?'#cfff45':v<=200?'#ffe23b':v<=300?'#ff9d32':'#ff3b3b'}
function setPing(v){hud();const x=Math.max(0,Math.min(999,Math.round(n(v)))),p=$('ebPing18');p.textContent=x+' ms';p.style.color=pingColor(x);p.style.borderColor=pingColor(x)}
let connPlayers=[];function renderPlayers(a){hud();connPlayers=Array.isArray(a)?a:[];window.__ebP18=connPlayers;$('ebConnNum18').textContent=connPlayers.length;$('ebConnRows18').innerHTML=connPlayers.map(x=>'<div style="padding:4px 5px;border-bottom:1px solid #293040"><b>'+String(x.name||'Jugador').replace(/[&<>]/g,'')+(x.id===s.id?' ⭐':'')+'</b></div>').join('')}
function openName(){if(nickModal)return;nickModal=document.createElement('div');css(nickModal,'position:fixed;inset:0;z-index:2147483647;background:#0008;display:flex;align-items:center;justify-content:center');let old='Jugador';try{old=localStorage.getItem('elBromasNick')||'Jugador'}catch{}nickModal.innerHTML='<div style="width:210px;background:#07101b;border:1px solid #40c9ff;border-radius:8px;padding:10px;color:#fff;font:11px Arial"><div style="font-weight:bold;margin-bottom:6px">Nombre</div><input id="ebNameInput18" style="width:100%;height:28px;border:1px solid #59657a;border-radius:5px;background:#111927;color:#fff;padding:5px;font-size:11px" value="'+String(old).replace(/"/g,'&quot;')+'"><button id="ebNameSave18" type="button" style="margin-top:8px;width:100%;height:28px;border:1px solid #40c9ff;border-radius:5px;background:#202942;color:#fff;font-size:11px">Guardar</button></div>';document.body.appendChild(nickModal);$('ebNameSave18').onclick=saveName;$('ebNameInput18').focus();$('ebNameInput18').select()}
function saveName(){const i=$('ebNameInput18');const name=String(i?.value||'').replace(/[<>]/g,'').trim().slice(0,20)||'Jugador';try{localStorage.setItem('elBromasNick',name)}catch{}if(s?.connected)s.emit('player:name',name);nickModal?.remove();nickModal=null;renderPlayers(connPlayers.map(p=>p.id===s.id?({...p,name}):p))}
function toggleChat(){const p=$('ebChatP18'),b=$('ebChatA18'),o=p.style.display!=='none';p.style.display=o?'none':'block';b.textContent=o?'↑':'↓'}
function focusChat(){const p=$('ebChatP18'),i=$('ebChatI18');p.style.display='block';$('ebChatA18').textContent='↓';setTimeout(()=>{i?.focus()},30)}
function hideKeyboard(){const i=$('ebChatI18');try{i?.blur();document.activeElement?.blur()}catch{}}
function sendChat(){const i=$('ebChatI18');if(!i){return}const t=i.value.trim().slice(0,120);if(t&&s?.connected){s.emit('chat:send',t);i.value='';hideKeyboard()}}
function addChat(d){hud();if(!d?.text)return;const name=String(d.name||'Jugador').replace(/[&<>]/g,''),text=String(d.text).replace(/[&<>]/g,'');$('ebChatLast18').textContent=name+': '+text;const r=document.createElement('div');r.style='padding:2px 1px;border-bottom:1px solid #293040;word-break:break-word';r.textContent=name+': '+text;const b=$('ebChatM18');b.appendChild(r);while(b.children.length>30)b.firstChild.remove();b.scrollTop=b.scrollHeight}
function removeRemoteNpcs(){try{for(const a of [smallPenes,activeMiniBosses])if(Array.isArray(a))for(let i=a.length-1;i>=0;i--)if(a[i]?.userData?.__ebRemoteNpc)a.splice(i,1);if(typeof boss!=='undefined'&&boss?.userData?.__ebRemoteNpc)boss=null}catch{}}
function localRadioState(){try{return window.__ebGetRadioState?.()||{}}catch{return{}}}
function remoteRadio(c){if(!c||c.owner===s.id||!c.radio?.enabled||!Number.isInteger(c.radio.station))return;const st=window.__ebGetRadioStation?.(c.radio.station);if(!st?.streamUrl)return;const map=window.__ebRemoteRadios18||(window.__ebRemoteRadios18=new Map);let r=map.get(c.index);if(!r||r.station!==c.radio.station||r.url!==st.streamUrl){try{r?.audio.pause()}catch{}const a=new Audio(st.streamUrl);a.loop=true;a.volume=.18;map.set(c.index,{audio:a,station:c.radio.station,url:st.streamUrl});a.play().catch(()=>{})}}
function syncCars(a){if(!Array.isArray(a))return;for(const c of a){if(c.owner!==s.id)remoteRadio(c);else if(c.radio&&window.__ebSetRadioState18){try{window.__ebSetRadioState18(c.radio)}catch{}}}const map=window.__ebRemoteRadios18;if(map)for(const[i]of map)if(!a.some(c=>Number(c.index)===Number(i)&&c.radio?.enabled))try{map.get(i).audio.pause();map.delete(i)}catch{}}
function carFix(){if(window.__EB_CAR18)return;window.__EB_CAR18=1;const original=window.__EB_ENTER_ORIG14||window.enterNearestCar;if(typeof original==='function'){window.enterNearestCar=function(){let i=-1,bd=64;try{for(let j=0;j<(drivableCars?.length||0);j++){const c=drivableCars[j];if(!c?.parent)continue;const dx=character.position.x-c.position.x,dz=character.position.z-c.position.z,d=dx*dx+dz*dz;if(d<bd){bd=d;i=j}}}catch{}if(i<0)return original();const busy=(window.__ebP18||[]).some(p=>p.id!==s.id&&p.driving&&p.carIndex===i);if(busy)return;try{original();setTimeout(()=>{try{if(drivenCar){drivenCar.userData=drivenCar.userData||{};drivenCar.userData.__ebLocalDrive=true;window.__ebCar18=i;s?.emit('car:claim',i)}}catch{}},30)}catch{return original()}}}const ex=window.exitDrivenCar;if(typeof ex==='function'&&!ex.__EB18){const wrap=function(){let i=-1;try{i=Array.isArray(drivableCars)&&drivenCar?drivableCars.indexOf(drivenCar):-1}catch{}const r=ex.apply(this,arguments);if(i>=0){try{drivableCars[i].userData.__ebLocalDrive=false}catch{}s?.emit('car:release',i);window.__ebCar18=-1}return r};wrap.__EB18=1;window.exitDrivenCar=wrap}}
function cinematic(d){if(!d)return;const b=d.boss,bar=$('bossHealthBar'),fill=$('bossHealthFill'),name=$('bossName');if(b&&n(b.hp)>0){if(bar&&fill){bar.style.display='block';fill.style.width=Math.max(0,Math.min(100,n(b.hp)/Math.max(1,n(b.maxHp,1))*100))+'%';bar.style.width=b.giant?'350px':'220px'}if(name){name.style.display='block';name.textContent=b.giant?'👹 PENE GIGANTE SUPREMO':'👹 PENE GIGANTE'}}else{if(bar)bar.style.display='none';if(name)name.style.display='none'}if(d.active&&d.cam&&!source){try{window.__ebApplyCameraState?.(d.cam)}catch{}}}
function radioTick(){try{const st=localRadioState();if(!st.driving){lastRadioKey='';return}const key=[st.carIndex,!!st.enabled,Number.isInteger(st.station)?st.station:-1].join('|');if(key!==lastRadioKey){lastRadioKey=key;s?.emit('car:radio:set',{index:Number(st.carIndex),enabled:!!st.enabled,station:Number.isInteger(st.station)?st.station:-1})}}catch{}}
function start(){hud();if(!s){setTimeout(start,500);return}if(s.__eb18)return;s.__eb18=1;s.on('connect',()=>{source=false});s.on('room:welcome',d=>{source=!!d.npcSource;renderPlayers(d.players||[]);syncCars(d.cars||[]);if(d.worldTime!=null)window.__ebTimeSnap18=n(d.worldTime);cinematic(d.cinematicState||d.gameState?.cinematicState||d.gameState)});s.on('room:sync',d=>{renderPlayers(d.players||[]);syncCars(d.cars||[]);if(d.worldTime!=null)window.__ebTimeSnap18=n(d.worldTime);cinematic(d.cinematicState||d.gameState?.cinematicState||d.gameState)});s.on('room:players',renderPlayers);s.on('online:count',x=>{$('ebConnNum18')&&($('ebConnNum18').textContent=Math.max(0,Math.floor(n(x))))});s.on('chat:message',addChat);s.on('latency:server',setPing);s.on('world:time',x=>{window.__ebTimeSnap18=n(x);if(!source)try{window.__ebSetTimeOfDay?.(n(x))}catch{}});s.on('cinematic:state',d=>{cinematic(d);if(d?.epoch||d?.startedAt)lastCinSig=String(d.epoch||d.startedAt)});s.on('car:state',d=>{if(d?.index!=null)syncCars([d])});s.on('car:claim:ok',d=>{try{window.__ebCar18=Number(d.index);if(d.radio&&window.__ebSetRadioState18)window.__ebSetRadioState18(d.radio)}catch{}});setInterval(()=>{if(!s.connected)return;const t=performance.now();s.emit('latency:ping',t,r=>setPing(performance.now()-(Number.isFinite(+r?.echo)?+r.echo:t)));radioTick();removeRemoteNpcs();if(!source&&window.__ebTimeSnap18!=null)try{window.__ebSetTimeOfDay?.(window.__ebTimeSnap18)}catch{}},1000);setInterval(()=>{if(!s.connected||!source)return;try{const c=window.__ebGetCinematicState?.();if(c){const sig=JSON.stringify(c);if(sig!==lastCinSig){lastCinSig=sig;s.emit('cinematic:state',c)}}const t=window.__ebGetTimeOfDay?.();if(Number.isFinite(+t)&&Math.abs(t-lastTime)>0.0000001){lastTime=t;s.emit('world:time',+t)}}catch{}},120);setInterval(()=>{try{syncCars(window.__ebGetCarsState?.()||[])}catch{}},300);carFix()}
start()})();