(()=>{
if(window.__EB_FINAL22)return;window.__EB_FINAL22=1;
const s=window.__ebSocket,N=v=>Number.isFinite(+v)?+v:0,$=id=>document.getElementById(id);
let passengerCar=-1,lastCar=-1,lastNear=0,lastUi=0,radioTimers=new Map(),eventState=null,originalEmit=null;
function carList(){return Array.isArray(window.__ebP18B)?window.__ebP18B:[]}
function distance2(c){try{if(typeof character==='undefined'||!c)return 1e9;const dx=N(character.position.x)-N(c.position.x),dz=N(character.position.z)-N(c.position.z);return dx*dx+dz*dz}catch{return 1e9}}
function carDriver(i){try{const p=carList().find(x=>x&&x.id!==s?.id&&x.driving&&Number(x.carIndex)===i);if(p)return p;const c=window.__ebCarState20?.get?.(i);return c?.owner&&c.owner!==s?.id?c:null}catch{return null}}
function nearestBusy(){try{if(!Array.isArray(drivableCars))return-1;let best=-1,bd=196;for(let i=0;i<drivableCars.length;i++){const c=drivableCars[i];if(!c?.parent)continue;const d=distance2(c);if(d<bd&&carDriver(i)){bd=d;best=i}}return best}catch{return-1}}
function passengerButton(){let b=$('ebPassenger22');if(b)return b;b=document.createElement('button');b.id='ebPassenger22';b.type='button';b.textContent='Pasajero';b.style.cssText='position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2147483647;display:none;min-width:120px;height:48px;padding:0 18px;border:2px solid #40c9ff;border-radius:9px;background:#07101bf5;color:#fff;font:bold 15px Arial;box-shadow:0 4px 18px #0008;pointer-events:auto;touch-action:manipulation;-webkit-tap-highlight-color:transparent';const go=e=>{e?.preventDefault?.();e?.stopPropagation?.();enterPassenger(lastCar)};b.addEventListener('touchstart',go,{passive:false});b.addEventListener('click',go);document.body.appendChild(b);return b}
function pauseMusic(){try{for(const a of document.querySelectorAll('audio,video')){if(!/^radio/i.test(a.id||''))a.pause?.()}for(const k of ['backgroundMusic','musicAudio','gameMusic','bgMusic','music','audio']){const a=window[k];if(a?.pause)a.pause()}}catch{}}
function restoreRadio(i,radio){try{const r=radio||window.__ebCarState20?.get?.(i)?.radio;if(!r)return;if(typeof window.__ebSetRadioState18==='function')window.__ebSetRadioState18(r);else{if(typeof carRadioStationIndex!=='undefined')carRadioStationIndex=N(r.station,-1);if(typeof carRadioEnabled!=='undefined')carRadioEnabled=!!r.enabled;if(typeof startCarRadio==='function')startCarRadio(false);if(typeof updateCarRadioUI==='function')updateCarRadioUI()}}catch{}}
function enterPassenger(i){try{if(i<0||!carDriver(i)||!Array.isArray(drivableCars))return;const c=drivableCars[i];if(!c?.parent||typeof character==='undefined')return;passengerCar=i;window.__ebPassenger18=true;window.__ebPassengerMode20=true;character.userData=character.userData||{};character.userData.__ebPassenger=true;character.position.set(N(c.position.x)+1.1,N(c.position.y),N(c.position.z));character.rotation.y=N(c.rotation.y);s?.emit('car:passenger:claim',i);pauseMusic();setTimeout(()=>restoreRadio(i),120)}catch{}}
function monitor(){const b=passengerButton();const inPass=passengerCar>=0||!!window.__ebPassenger18||!!window.__ebPassengerMode20;if(inPass){b.style.display='none';return}const i=nearestBusy();if(i>=0){lastCar=i;b.style.display='block'}else b.style.display='none'}
function patchEnter(){try{const fn=window.enterNearestCar;if(typeof fn!=='function'||fn.__eb22)return;if(window.__eb22OrigEnter)return;window.__eb22OrigEnter=fn;const wrap=function(...a){const i=nearestBusy();if(i>=0){enterPassenger(i);return}return fn.apply(this,a)};wrap.__eb22=true;window.enterNearestCar=wrap}catch{}}
function patchRadioSetter(){if(typeof window.__ebSetRadioState18==='function')return;window.__ebSetRadioState18=function(r){try{if(!r)return;if(typeof carRadioStationIndex!=='undefined')carRadioStationIndex=N(r.station,-1);if(typeof carRadioEnabled!=='undefined')carRadioEnabled=!!r.enabled;if(typeof startCarRadio==='function')startCarRadio(false);if(typeof updateCarRadioUI==='function')updateCarRadioUI()}catch{}}}
function delayNet(){if(!s||s.__eb22Emit)return;s.__eb22Emit=true;originalEmit=s.emit.bind(s);s.emit=function(ev,...args){const now=performance.now();const t=s.__eb22LastSend||(s.__eb22LastSend={});const limits={'npc:snapshot':180,'game:state':300,'fx:snapshot':160,'world:snapshot':250,'world:ui':250,'world:visual':500,'world:time':500,'player:state':75};if(ev==='car:radio:set'&&args[0]?.index!==undefined){const d={...args[0]},i=Number(d.index);clearTimeout(radioTimers.get(i));radioTimers.set(i,setTimeout(()=>{radioTimers.delete(i);try{originalEmit(ev,d)}catch{}},4000));return s}const lim=limits[ev];if(lim&&now-(t[ev]||0)<lim)return s;t[ev]=now;if(ev==='game:state'&&args[0]&&typeof args[0]==='object'){const d={...args[0]};const mt=$('missionTitle'),mp=$('missionProgress'),mu=$('missionUI');if(mt)d.missionTitle=String(mt.textContent||'').trim().slice(0,220);if(mp)d.missionProgress=String(mp.textContent||'').trim().slice(0,220);if(mu)d.missionVisible=getComputedStyle(mu).display!=='none';args[0]=d}return originalEmit(ev,...args)};}
function syncEvent(g){try{eventState=g||eventState;const title=String(g?.missionTitle||'').trim(),prog=String(g?.missionProgress||'').trim();const ui=$('missionUI'),mt=$('missionTitle'),mp=$('missionProgress');if(ui&&!s.__eb22Host){if(title&&mt)mt.textContent=title;if(prog&&mp)mp.textContent=prog;if(g?.mission||g?.missionTitle){ui.style.display=g.missionVisible===false?'none':'block'}else if(g?.mission===false&&title)ui.style.display='none'}const rep=$('ebRepUi18');if(rep)rep.style.display='none'}catch{}}
function eventFromUi(a){try{if(!Array.isArray(a)||s.__eb22Host)return;let title='',prog='',visible=false;for(const x of a){const id=String(x?.id||'').toLowerCase();if(id==='missiontitle')title=String(x.text||'').trim();if(id==='missionprogress')prog=String(x.text||'').trim();if(id==='missionui')visible=true}if(title||prog)syncEvent({mission:visible||!!title,missionTitle:title,missionProgress:prog,missionVisible:visible||!!title})}catch{}}
function chatFix(){const a=$('ebChatArrow16');if(a&&a.dataset.eb22!=='1'){a.dataset.eb22='1';a.onclick=e=>{e?.preventDefault?.();e?.stopPropagation?.();const p=$('ebChatPanel16');if(p)p.style.display=p.style.display==='none'?'block':'none'}}const l=$('ebChatLast16');if(l)l.title='Toca aquí para escribir';}
function uiFix(){const p=$('ebPlayers16');if(p){p.style.left='10px';p.style.right='auto'}chatFix();patchRadioSetter();patchEnter();}
function start(){if(!s){setTimeout(start,300);return}delayNet();if(!s.__eb22Events){s.__eb22Events=true;s.on('game:state',syncEvent);s.on('room:welcome',d=>{s.__eb22Host=!!d?.npcSource;syncEvent(d?.gameState)});s.on('room:sync',d=>{syncEvent(d?.gameState)});s.on('world:ui',eventFromUi);s.on('car:passenger:ok',d=>{passengerCar=N(d?.index,-1);window.__ebPassenger18=true;window.__ebPassengerMode20=true;pauseMusic();restoreRadio(passengerCar,d?.radio)});s.on('car:passenger:deny',()=>{passengerCar=-1;window.__ebPassenger18=false;window.__ebPassengerMode20=false});s.on('car:state',d=>{if(Number(d?.index)===passengerCar)restoreRadio(passengerCar,d?.radio)});s.on('room:welcome',d=>{for(const c of d?.cars||[])if(Number(c?.index)===passengerCar)restoreRadio(passengerCar,c.radio)});s.on('room:sync',d=>{for(const c of d?.cars||[])if(Number(c?.index)===passengerCar)restoreRadio(passengerCar,c.radio)})}requestAnimationFrame(function tick(t){if(t-lastNear>140){lastNear=t;monitor();uiFix()}if(t-lastUi>240){lastUi=t;uiFix()}requestAnimationFrame(tick)})}
setTimeout(start,500);
})();
