(()=>{if(window.__EB_FINAL26)return;window.__EB_FINAL26=1;const s=window.__ebSocket,N=v=>Number.isFinite(+v)?+v:0;let radios=new Map,lastRadioKey=new Map,lastWorldKey='',emptySince=0,warning=null,warningTimer=null,clock=-1;
function cars(){try{return Array.isArray(drivableCars)?drivableCars:[]}catch{return[]}}
function myCar(){try{if(typeof drivenCar!=='undefined'&&drivenCar){const i=cars().indexOf(drivenCar);if(i>=0)return{index:i,car:drivenCar}}}catch{}const ps=window.__ebP18B||[],me=ps.find(p=>p.id===s?.id);return me?.driving&&me.carIndex>=0?{index:me.carIndex,car:cars()[me.carIndex]}:null}
function applyCar(c){try{if(!c||c.index===undefined)return;const i=Math.floor(N(c.index,-1)),o=cars()[i];if(!o||o.userData?.__ebLocalDrive)return;o.position.set(N(c.x),N(c.y),N(c.z));o.rotation.y=N(c.ry);o.userData=o.userData||{};o.userData.speed=N(c.speed);o.userData.__ebNetVehicle=true;o.visible=c.visible!==false}catch{}}
function radioApply(index,r){try{if(!Number.isInteger(index)||!r||!Number.isInteger(+r.station))return;const station=Math.max(0,Math.floor(+r.station)),enabled=!!r.enabled;radios.set(index,{station,enabled});window.__ebServerRadio26={index,station,enabled};if(index!==myCar()?.index)return;if(typeof carRadioStationIndex!=='undefined')carRadioStationIndex=station;if(typeof carRadioEnabled!=='undefined')carRadioEnabled=enabled;window.__ebRadioStation26=station;window.__ebRadioEnabled26=enabled;try{if(typeof window.__ebSetRadioState18==='function')window.__ebSetRadioState18({station,enabled})}catch{}try{if(typeof updateCarRadioUI==='function')updateCarRadioUI()}catch{}if(enabled)setTimeout(()=>{try{if(typeof startCarRadio==='function')startCarRadio(false)}catch{}},30)}catch{}}
function radioRead(){try{const m=myCar();if(!m)return;let station=-1,enabled=false;if(typeof carRadioStationIndex!=='undefined')station=Math.floor(N(carRadioStationIndex,-1));if(typeof carRadioEnabled!=='undefined')enabled=!!carRadioEnabled;if(station<0)return;const key=station+':'+(enabled?1:0);if(lastRadioKey.get(m.index)!==key){lastRadioKey.set(m.index,key);s?.emit('car:radio:set',{index:m.index,station,enabled})}}catch{}}
function radioLoad(d){try{for(const x of d||[])if(Number.isInteger(+x.index)&&x.radio)radios.set(Math.floor(+x.index),x.radio);for(const[i,r]of radios)radioApply(i,r)}catch{}}
function worldCollect(){const out=[];const add=(arr,type)=>{if(!Array.isArray(arr))return;arr.forEach((o,i)=>{if(!o)return;const u=o.userData||{};if(!o.parent&&!u.__ebKeepWorld)return;out.push({id:'structure:'+type+':'+i,type:'structure',group:type,index:i,x:N(o.position?.x),y:N(o.position?.y),z:N(o.position?.z),rx:N(o.rotation?.x),ry:N(o.rotation?.y),rz:N(o.rotation?.z),sx:N(o.scale?.x,1),sy:N(o.scale?.y,1),sz:N(o.scale?.z,1),visible:o.visible!==false,destroyed:!!u.destroyed,state:N(u.health,u.state)})})};try{add(window.destructibleProps,'destructibleProps');add(window.trees,'trees');add(window.structures,'structures');add(window.buildings,'buildings');add(window.worldStructures,'worldStructures')}catch{}return out}
function worldSend(){try{const items=worldCollect(),key=JSON.stringify(items);if(key!==lastWorldKey){lastWorldKey=key;s?.emit('eb:world:state',{items})}}catch{}}
function worldApply(items){try{if(!Array.isArray(items))return;const groups={destructibleProps:window.destructibleProps,trees:window.trees,structures:window.structures,buildings:window.buildings,worldStructures:window.worldStructures};for(const w of items){if(w?.type!=='structure')continue;const a=groups[w.group],o=Array.isArray(a)?a[w.index]:null;if(!o)continue;o.position?.set(N(w.x),N(w.y),N(w.z));o.rotation?.set(N(w.rx),N(w.ry),N(w.rz));o.scale?.set(N(w.sx,1),N(w.sy,1),N(w.sz,1));o.visible=w.visible!==false&&!w.destroyed;o.userData=o.userData||{};o.userData.destroyed=!!w.destroyed;if(w.state!==undefined)o.userData.health=N(w.state,w.state)}}catch{}}
function warningBox(){if(!warning){warning=document.createElement('div');warning.id='ebZeroNpcWarning26';warning.style.cssText='position:fixed;left:50%;top:14%;transform:translateX(-50%);z-index:2147483647;display:none;padding:8px 18px;border:2px solid #fff;border-radius:7px;background:#050505dd;color:#fff;font:bold 18px Arial;text-align:center;pointer-events:none;text-shadow:0 1px 3px #000';document.body.appendChild(warning)}return warning}
function warningStart(){if(warningTimer)return;warningTimer=setInterval(()=>{const e=warningBox();if(!emptySince){e.style.display='none';return}const sec=(Date.now()-emptySince)/1000;if(sec<3){e.style.display='none';return}if(sec<9){e.textContent='¡NO QUEDAN NPC VIVOS!';e.style.borderColor='#fff';e.style.color='#fff';e.style.display=Math.floor(Date.now()/350)%2?'block':'none'}else if(sec<15){e.textContent='¡PELIGRO! 15 SEGUNDOS';e.style.borderColor='#f00';e.style.color='#f00';e.style.display=Math.floor(Date.now()/110)%2?'block':'none'}else{e.textContent='¡REVIVIENDO NPC!';e.style.borderColor='#f00';e.style.color='#f00';e.style.display='block'}},100)}
function emptyState(g){const alive=Math.max(0,Math.floor(N(g?.alive,-1)));if(alive===0){if(!emptySince)emptySince=Date.now();warningStart()}else{emptySince=0;warningBox().style.display='none'}}
function applyClock(t){if(!Number.isFinite(+t))return;clock=+t;window.__ebServerDayTime=clock;const a=(clock/24)*Math.PI*2-Math.PI/2,day=Math.max(0,Math.sin(a)*.5+.5);try{if(typeof scene==='undefined')return;let li=0;scene.traverse(o=>{if(li>=30)return;if(o.isAmbientLight||o.isDirectionalLight||o.isHemisphereLight||o.isPointLight){o.userData=o.userData||{};const base=o.userData.__ebDayBaseIntensity??N(o.intensity);o.userData.__ebDayBaseIntensity=base;o.intensity=base*(.28+.72*day);li++}})}catch{}}
s?.on('car:state',d=>{if(d?.index!==undefined){applyCar(d);if(d.radio)radioApply(Math.floor(N(d.index)),d.radio)}});s?.on('car:radio:state',d=>{if(d?.index!==undefined&&d.radio)radioApply(Math.floor(N(d.index)),d.radio)});s?.on('room:welcome',d=>{radioLoad(d?.radioState);for(const c of d?.cars||[])if(c?.index!==undefined){applyCar(c);if(c.radio)radioApply(Math.floor(N(c.index)),c.radio)}if(d?.worldSnapshot?.items)worldApply(d.worldSnapshot.items);if(d?.worldTime!==undefined)applyClock(d.worldTime);emptyState(d?.gameState)});s?.on('room:sync',d=>{radioLoad(d?.radioState);for(const c of d?.cars||[])if(c?.index!==undefined){applyCar(c);if(c.radio)radioApply(Math.floor(N(c.index)),c.radio)}if(d?.worldSnapshot?.items)worldApply(d.worldSnapshot.items);if(d?.worldTime!==undefined)applyClock(d.worldTime);emptyState(d?.gameState)});s?.on('world:snapshot',m=>worldApply(m?.items));s?.on('world:state',m=>worldApply(m?.items));s?.on('world:time',d=>applyClock(d?.time));s?.on('game:state',emptyState);s?.on('npc:snapshot',m=>emptyState({alive:Array.isArray(m?.items)?m.items.length:0}));s?.on('npc:revived',()=>{emptySince=0;warningBox().style.display='none'});setInterval(()=>{radioRead();for(const[i,r]of radios)radioApply(i,r);worldSend();if(clock>=0)applyClock(clock)},500);})();
