(()=>{
if(window.__EB_FINAL21)return;window.__EB_FINAL21=1;
const s=window.__ebSocket,N=v=>Number.isFinite(+v)?+v:0,$=id=>document.getElementById(id);
/* Passenger control: every client gets the same center button when a nearby car has another driver. */
let passengerCar=-1,lastCar=-1,lastCheck=0,radioTimers=new Map();
function cars(){return Array.isArray(window.__ebP18B)?window.__ebP18B:[]}
function nearest(){try{if(typeof character==='undefined'||!Array.isArray(drivableCars))return-1;let bi=-1,bd=64;for(let i=0;i<drivableCars.length;i++){const c=drivableCars[i];if(!c?.parent)continue;const dx=N(character.position.x)-N(c.position.x),dz=N(character.position.z)-N(c.position.z),d=dx*dx+dz*dz;if(d<bd){bd=d;bi=i}}return bi}catch{return-1}}
function driver(i){const a=cars().find(p=>p&&p.id!==s?.id&&p.driving&&p.carIndex===i);if(a)return a;const m=window.__ebCarState20?.get?.(i);return m?.owner&&m.owner!==s?.id?m:null}
function passengerButton(){let b=$('ebPassenger21');if(b)return b;b=document.createElement('button');b.id='ebPassenger21';b.type='button';b.textContent='Pasajero';b.style.cssText='position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2147483646;display:none;min-width:110px;height:44px;padding:0 16px;border:2px solid #40c9ff;border-radius:9px;background:#07101bf5;color:#fff;font:bold 14px Arial;box-shadow:0 4px 18px #0008;touch-action:manipulation';b.onclick=e=>{e.preventDefault();e.stopPropagation();enterPassenger(lastCar)};document.body.appendChild(b);return b}
function enterPassenger(i){try{if(i<0||!driver(i)||!Array.isArray(drivableCars))return;const c=drivableCars[i];if(!c?.parent||typeof character==='undefined')return;passengerCar=i;window.__ebPassengerMode20=true;character.userData=character.userData||{};character.userData.__ebPassenger=true;character.position.set(N(c.position.x)+1.1,N(c.position.y),N(c.position.z));character.rotation.y=N(c.rotation.y);s?.emit('car:passenger:claim',i);pauseMusic();setTimeout(()=>restoreRadio(i),80)}catch{}}
function pauseMusic(){try{for(const a of document.querySelectorAll('audio,video')){if(!a.id||!/^radio/i.test(a.id))a.pause?.()}for(const k of ['backgroundMusic','musicAudio','gameMusic','bgMusic','music','audio']){const a=window[k];if(a?.pause)a.pause()}}catch{}}
function restoreRadio(i){try{const d=window.__ebCarState20?.get?.(i),r=d?.radio;if(r&&window.__ebSetRadioState18){window.__ebSetRadioState18(r);window.updateCarRadioUI?.()}}catch{}}
function monitor(){const b=passengerButton();const inPass=passengerCar>=0||!!window.__ebPassenger18||!!window.__ebPassengerMode20;if(inPass){b.style.display='none';return}const i=nearest();if(i>=0&&driver(i)){lastCar=i;b.style.display='block'}else b.style.display='none'}
function moveConnected(){const p=$('ebPlayers16');if(p){p.style.left='10px';p.style.right='auto'}const chat=$('ebChat16');if(chat){chat.style.pointerEvents='auto'}const arrow=$('ebChatArrow16');if(arrow&&arrow.dataset.eb21!=='1'){arrow.dataset.eb21='1';const old=arrow.onclick;arrow.onclick=e=>{e?.preventDefault?.();e?.stopPropagation?.();const panel=$('ebChatPanel16');if(panel){const open=panel.style.display==='none';panel.style.display=open?'block':'none';arrow.textContent=open?'↓':'↑'}}}const last=$('ebChatLast16');if(last)last.title='Toca aquí para escribir'}
function delayRadio(){if(!s||s.__ebRadio21)return;s.__ebRadio21=true;const original=s.emit.bind(s);s.emit=function(ev,...args){if(ev==='car:radio:set'&&args[0]?.index!==undefined){const d={...args[0]},i=Number(d.index);clearTimeout(radioTimers.get(i));const timer=setTimeout(()=>{radioTimers.delete(i);try{original(ev,d)}catch{}},4000);radioTimers.set(i,timer);return s}return original(ev,...args)};}
function tick(t){if(t-lastCheck>160){lastCheck=t;monitor();moveConnected();delayRadio()}requestAnimationFrame(tick)}
function radioRestoreEvents(){if(!s||s.__ebRadioRestore21)return;s.__ebRadioRestore21=1;s.on('car:passenger:ok',d=>{passengerCar=Number(d?.index);window.__ebPassengerMode20=true;pauseMusic();restoreRadio(passengerCar)});s.on('car:passenger:deny',()=>{passengerCar=-1});s.on('car:state',d=>{if(d?.index!==undefined&&Number(d.index)===passengerCar&&d.radio)restoreRadio(passengerCar)});s.on('room:welcome',d=>{for(const c of d?.cars||[])if(c?.index!==undefined&&c.radio&&Number(c.index)===passengerCar)restoreRadio(passengerCar)});s.on('room:sync',d=>{for(const c of d?.cars||[])if(c?.index!==undefined&&c.radio&&Number(c.index)===passengerCar)restoreRadio(passengerCar)})}
function start(){radioRestoreEvents();if(typeof requestAnimationFrame==='function')requestAnimationFrame(tick);else setTimeout(start,250)}setTimeout(start,250);
})();