(()=>{if(window.__EB_NET15)return;window.__EB_NET15=1;const s=window.__ebSocket;let pingBox=null,playersBox=null;
const $=id=>document.getElementById(id);
function ui(){if(!pingBox){pingBox=$('ebPing');if(!pingBox){pingBox=document.createElement('div');pingBox.id='ebPing';pingBox.style='position:fixed;top:10px;right:10px;z-index:2147483647;background:#07101bf2;border:1px solid #40c9ff;border-radius:12px;padding:6px 10px;font:bold 12px Arial;';document.body.appendChild(pingBox)}pingBox.textContent='-- ms'}if(!playersBox){playersBox=document.createElement('div');playersBox.id='ebPlayers';playersBox.style='position:fixed;top:48px;right:10px;z-index:2147483647;background:#07101bf2;color:#fff;border:1px solid #40c9ff;border-radius:12px;padding:6px 10px;font:bold 12px Arial;';playersBox.textContent='👥 Jugadores: 0';document.body.appendChild(playersBox)}}
function pingColor(ms){if(ms<=45)return'#b8ffb8';if(ms<=80)return'#72ff72';if(ms<=130)return'#cfff45';if(ms<=200)return'#ffe23b';if(ms<=300)return'#ff9d32';return'#ff3b3b'}
function setPing(ms){ui();ms=Math.max(0,Math.min(999,Math.round(Number(ms)||0)));pingBox.textContent=ms+' ms';pingBox.style.color=pingColor(ms);pingBox.style.borderColor=pingColor(ms)}
function setPlayers(n){ui();playersBox.textContent='👥 Jugadores: '+Math.max(0,Math.floor(Number(n)||0))}
function installPing(){ui();if(!s||s.__ebPing15)return;s.__ebPing15=1;let last=0;s.on('latency:server',x=>{if(Number.isFinite(+x))setPing(x)});s.on('online:count',setPlayers);s.on('room:players',a=>setPlayers(Array.isArray(a)?a.length:0));s.on('connect',()=>setPlayers(1));setInterval(()=>{if(!s.connected)return;const t=performance.now();s.emit('latency:ping',t,r=>{const ms=performance.now()-Number(r?.echo||t);setPing(ms)})},1000)}
function car(){if(window.__EB_CAR15)return;window.__EB_CAR15=1;const orig=window.__EB_ENTER_ORIG14||window.enterNearestCar;if(typeof orig!=='function')return;window.__EB_ENTER_ORIG15=orig;window.enterNearestCar=function(){let i=-1,bd=64;try{if(Array.isArray(drivableCars)&&typeof character!=='undefined')for(let j=0;j<drivableCars.length;j++){const c=drivableCars[j];if(!c?.parent)continue;const dx=character.position.x-c.position.x,dz=character.position.z-c.position.z,d=dx*dx+dz*dz;if(d<bd){bd=d;i=j}}}catch{}if(i<0)return orig();try{const busy=(Array.isArray(window.__ebNetPlayers)?window.__ebNetPlayers:[]).some(p=>p.id!==window.__ebNetSelf&&p.driving&&p.carIndex===i);if(busy)return;}catch{}orig();if(s?.connected)s.emit('car:claim',i)};s?.on('room:players',a=>window.__ebNetPlayers=a||[]);s?.on('room:welcome',d=>{window.__ebNetSelf=d?.id;window.__ebNetPlayers=d?.players||[]});s?.on('room:sync',d=>{window.__ebNetPlayers=d?.players||[]});s?.on('car:claim:deny',()=>{try{if(typeof exitDrivenCar==='function')exitDrivenCar()}catch{}})}
function start(){ui();installPing();car();setTimeout(start,5000)}start()})();
