(()=>{
if(window.__EB_ONLINE_CORE)return;window.__EB_ONLINE_CORE=1;
const S=()=>window.__ebSocket,N=(v,d=0)=>Number.isFinite(+v)?+v:d;
const nick=()=>{try{return(localStorage.getItem('elBromasNick')||'Jugador').trim().slice(0,20)||'Jugador'}catch{return'Jugador'}};
const saveNick=v=>{try{localStorage.setItem('elBromasNick',v)}catch{}};
let players=[],remotes=new Map(),lastSend=0,lastRound=0,connected=false,ui=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pose(){const out={},u=typeof character!=='undefined'?(character?.userData||{}):{};['hips','torsoGroup','headGroup','leftShoulder','leftUpperArm','leftElbow','rightShoulder','rightUpperArm','rightElbow','nalgasGroup','leftThigh','leftKnee','rightThigh','rightKnee','tuboGroup'].forEach(k=>{const r=u[k]?.rotation;if(r)out[k]=[r.x,r.y,r.z]});return out}
function state(){if(typeof character==='undefined'||!character?.position)return null;let hp=100,aura=0,kills=0;try{hp=N(typeof playerHealth!=='undefined'?playerHealth:100,100)}catch{}try{aura=N(typeof playerAura!=='undefined'?playerAura:0)}catch{}try{kills=N(typeof totalPenesKilled!=='undefined'?totalPenesKilled:0)}catch{}return{name:nick(),x:N(character.position.x),y:N(character.position.y),z:N(character.position.z),rx:N(character.rotation.x),ry:N(character.rotation.y),rz:N(character.rotation.z),hp,aura,kills,dead:!!(typeof isDead!=='undefined'&&isDead),moving:!!(typeof isMoving!=='undefined'&&isMoving),running:!!(typeof isRunning!=='undefined'&&isRunning),jumping:!!(typeof isJumping!=='undefined'&&isJumping),flying:!!(typeof isFlying!=='undefined'&&isFlying),attacking:!!(typeof isAttacking!=='undefined'&&isAttacking),special:!!(typeof isSpecialAttacking!=='undefined'&&isSpecialAttacking),attackPhase:N(typeof attackPhase!=='undefined'?attackPhase:0),specialPhase:N(typeof specialPhase!=='undefined'?specialPhase:0),walkCycle:N(typeof walkCycle!=='undefined'?walkCycle:0),round:N(typeof waveNumber!=='undefined'?waveNumber:0),pose:pose()}}
function makeLabel(text){if(typeof THREE==='undefined')return null;const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d');x.clearRect(0,0,512,96);x.font='bold 42px Arial';x.textAlign='center';x.textBaseline='middle';x.lineWidth=8;x.strokeStyle='rgba(0,0,0,.85)';x.strokeText(String(text||'Jugador').slice(0,20),256,48);x.fillStyle='#fff';x.fillText(String(text||'Jugador').slice(0,20),256,48);const tex=new THREE.CanvasTexture(c);tex.needsUpdate=true;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.scale.set(2.7,.5,1);sp.position.y=2.8;sp.userData.__ebLabelCanvas=c;sp.userData.__ebLabelTex=tex;return sp}
function setLabel(r,name){if(!r)return;if(r.name===name&&r.label)return;r.name=name||'Jugador';if(r.label?.parent)r.label.parent.remove(r.label);r.label=makeLabel(r.name);if(r.label)r.g.add(r.label)}
function addRemote(p){if(!p||!p.id||p.id===S()?.id||remotes.has(p.id)||typeof scene==='undefined'||typeof createCharacterWithSkeleton!=='function')return;try{const g=createCharacterWithSkeleton();if(!g)return;g.userData=g.userData||{};g.userData.__ebRemote=true;g.userData.__ebRemoteId=p.id;scene.add(g);const r={g,name:'',label:null};remotes.set(p.id,r);setLabel(r,p.name)}catch(e){console.warn('remote avatar',e)}}
function draw(){if(!ui)return;ui.list.innerHTML='<b>Conectados</b><button id="ebNickBtn" type="button">✏️</button>'+players.map(p=>'<div class="ebRow '+(p.id===S()?.id?'me':'')+'"><b>'+esc(p.name||'Jugador')+(p.id===S()?.id?' ⭐':'')+'</b><span>❤️ '+Math.round(N(p.hp,100))+'</span><span>🌀 '+Math.round(N(p.aura))+'</span><span>☠ '+Math.round(N(p.kills))+'</span></div>').join('');ui.list.querySelector('#ebNickBtn').onclick=rename}
function rename(){const v=prompt('Tu nombre',nick());if(v==null)return;const n=String(v).replace(/[<>]/g,'').trim().slice(0,20)||'Jugador';saveNick(n);S()?.emit('player:name',n);draw()}
function buildUi(){if(document.getElementById('ebCoreHud'))return;const st=document.createElement('style');st.textContent='#ebCoreHud{position:fixed;top:10px;right:10px;z-index:2147483000;font:900 13px Arial}#ebCoreBtn{border:1px solid #7280ff;border-radius:20px;background:#0c0f18ee;color:#fff;padding:9px 15px}#ebCoreList{display:none;position:fixed;right:10px;top:52px;width:min(430px,94vw);max-height:46vh;overflow:auto;z-index:2147482999;background:#080c15fa;color:#fff;border:1px solid #7280ff;border-radius:16px;padding:10px;box-sizing:border-box;font:12px Arial}.ebRow{display:grid;grid-template-columns:1fr auto auto auto;gap:7px;padding:9px;border-bottom:1px solid #293040}.ebRow.me{background:#5064ff2b;border-radius:8px}#ebNickBtn{float:right;border:0;background:transparent;color:#fff;font-size:17px}';document.head.appendChild(st);const h=document.createElement('div');h.id='ebCoreHud';h.innerHTML='<button id="ebCoreBtn" type="button">Conectados 0</button><div id="ebCoreList"></div>';document.body.appendChild(h);const b=h.querySelector('#ebCoreBtn'),list=h.querySelector('#ebCoreList');ui={list};b.onclick=()=>{list.style.display=getComputedStyle(list).display==='none'?'block':'none';draw()}}
function applyRemotes(){if(typeof scene==='undefined'||typeof THREE==='undefined')return;const ids=new Set(players.map(p=>p.id));players.forEach(addRemote);for(const[id,r]of remotes){const p=players.find(x=>x.id===id);if(!p){r.g.parent?.remove?.(r.g);r.label?.material?.map?.dispose?.();r.label?.material?.dispose?.();remotes.delete(id);continue}r.g.visible=!p.dead;setLabel(r,p.name);r.g.position.lerp(new THREE.Vector3(N(p.x),N(p.y),N(p.z)),.35);r.g.rotation.set(N(p.rx),N(p.ry),N(p.rz));for(const[k,v]of Object.entries(p.pose||{}))if(r.g.userData[k]?.rotation)r.g.userData[k].rotation.set(N(v[0]),N(v[1]),N(v[2]));r.g.userData.netMoving=!!p.moving;r.g.userData.netRunning=!!p.running;r.g.userData.netJumping=!!p.jumping;r.g.userData.netFlying=!!p.flying;r.g.userData.netAttacking=!!p.attacking;r.g.userData.netSpecial=!!p.special;r.g.userData.netAttackPhase=N(p.attackPhase);r.g.userData.netSpecialPhase=N(p.specialPhase);r.g.userData.netWalkCycle=N(p.walkCycle)} }
function loop(t){applyRemotes();requestAnimationFrame(loop)}
function send(t){const s=S();if(!s?.connected||t-lastSend<80)return;const d=state();if(!d)return;lastSend=t;s.emit('player:state',d);if(d.round!==lastRound){lastRound=d.round;s.emit('round:set',d.round)}}
function connect(){const s=S();if(!s||s.__EB_CORE_BOUND)return false;s.__EB_CORE_BOUND=1;s.on('connect',()=>{connected=true;s.emit('room:join',{name:nick(),round:N(typeof waveNumber!=='undefined'?waveNumber:1,1)})});s.on('disconnect',()=>{connected=false});s.on('room:welcome',d=>{players=Array.isArray(d?.players)?d.players:[];draw()});s.on('room:players',a=>{players=Array.isArray(a)?a:[];ui.list.previousElementSibling?.remove;draw();const b=document.getElementById('ebCoreBtn');if(b)b.textContent='Conectados '+players.length});s.on('round:state',r=>{const n=N(r);try{if(typeof waveNumber!=='undefined'&&n>Number(waveNumber||0)){waveNumber=n;updateWaveUI?.();updateHUD?.()}}catch{}});return true}
function start(){buildUi();if(connect()){if(S()?.connected)S().emit('room:join',{name:nick(),round:N(typeof waveNumber!=='undefined'?waveNumber:1,1)});requestAnimationFrame(loop);setInterval(()=>send(performance.now()),80)}else setTimeout(start,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();