(()=>{if(window.__EB_NET16)return;window.__EB_NET16=1;const s=window.__ebSocket||null,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));let ping,lastMsg='';
function css(el,x){el.style.cssText=x}
function ui(){
 if(!ping){ping=document.createElement('div');ping.id='ebPing16';css(ping,'position:fixed;top:10px;right:10px;z-index:2147483647;background:#07101bf2;border:2px solid #b8ffb8;border-radius:10px;padding:6px 10px;font:bold 13px Arial;color:#b8ffb8;min-width:58px;text-align:center;pointer-events:none');ping.textContent='0 ms';document.body.appendChild(ping)}
 let p=$('ebPlayers16');if(!p){p=document.createElement('div');p.id='ebPlayers16';css(p,'position:fixed;top:48px;right:10px;z-index:2147483647;background:#07101bf5;color:#fff;border:1px solid #40c9ff;border-radius:10px;font:bold 13px Arial;min-width:150px;overflow:hidden;box-shadow:0 4px 18px #0008');p.innerHTML='<div id="ebConnHead16" style="padding:9px 12px;cursor:pointer;user-select:none">Conectados: <span id="ebConnNum16">0</span></div><div id="ebConnList16" style="display:none;max-height:45vh;overflow:auto;border-top:1px solid #293040"><div style="position:sticky;top:0;background:#07101b;padding:7px 8px;text-align:right"><button id="ebName16" type="button" style="width:32px;height:30px;border:1px solid #7280ff;border-radius:7px;background:#202942;color:#fff;font-size:16px">✏️</button></div><div id="ebConnRows16"></div></div>';document.body.appendChild(p);$('ebConnHead16').onclick=()=>{const l=$('ebConnList16');l.style.display=l.style.display==='none'?'block':'none'};$('ebName16').onclick=rename}
 let c=$('ebChat16');if(!c){c=document.createElement('div');c.id='ebChat16';css(c,'position:fixed;left:50%;bottom:12px;transform:translateX(-50%);z-index:2147483647;width:min(430px,92vw);font:bold 13px Arial;color:#fff;pointer-events:auto');c.innerHTML='<div id="ebChatBar16" style="display:flex;align-items:center;gap:7px;background:#07101bf2;border:1px solid #40c9ff;border-radius:20px;padding:5px 7px;box-shadow:0 4px 18px #0008"><button id="ebChatArrow16" type="button" style="width:34px;height:34px;border:0;border-radius:50%;background:#202942;color:#fff;font-size:20px">↑</button><div id="ebChatLast16" style="flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#ddd">Chat</div></div><div id="ebChatPanel16" style="display:none;margin-bottom:6px;background:#07101bf5;border:1px solid #40c9ff;border-radius:12px;overflow:hidden"><div id="ebChatMsgs16" style="height:190px;max-height:35vh;overflow:auto;padding:8px"></div><div style="display:flex;gap:5px;padding:7px;border-top:1px solid #293040"><input id="ebChatInput16" maxlength="120" placeholder="Escribe un mensaje..." style="flex:1;min-width:0;border:1px solid #59657a;border-radius:8px;background:#111927;color:#fff;padding:8px"><button id="ebChatSend16" type="button" style="border:1px solid #40c9ff;border-radius:8px;background:#202942;color:#fff;padding:0 12px">Enviar</button></div></div>';document.body.appendChild(c);$('ebChatArrow16').onclick=()=>{const q=$('ebChatPanel16'),b=$('ebChatArrow16');const o=q.style.display!=='none';q.style.display=o?'none':'block';b.textContent=o?'↑':'↓';if(!o)$('ebChatInput16').focus()};$('ebChatSend16').onclick=sendChat;$('ebChatInput16').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendChat()}}}
}
function pingColor(n){return n<=45?'#b8ffb8':n<=80?'#72ff72':n<=130?'#cfff45':n<=200?'#ffe23b':n<=300?'#ff9d32':'#ff3b3b'}
function setPing(v){ui();const n=Math.max(0,Math.min(999,Math.round(Number(v)||0)));ping.textContent=n+' ms';ping.style.color=pingColor(n);ping.style.borderColor=pingColor(n)}
function players(a){ui();a=Array.isArray(a)?a:[];$('ebConnNum16').textContent=a.length;const self=window.__ebSelf16;$('ebConnRows16').innerHTML=a.map(p=>'<div style="display:flex;align-items:center;gap:8px;padding:8px 9px;border-bottom:1px solid #293040"><b style="flex:1">'+esc(p.name||'Jugador')+(p.id===self?' ⭐':'')+'</b><span>❤️ '+Math.round(Number(p.hp)||100)+'</span><span>🌀 '+Math.round(Number(p.aura)||0)+'</span><span>☠ '+Math.round(Number(p.kills)||0)+'</span></div>').join('')}
function rename(e){e?.stopPropagation();let old='Jugador';try{old=localStorage.getItem('elBromasNick')||'Jugador'}catch{}const v=prompt('Cambiar nombre',old);if(v===null)return;const n=String(v).replace(/[<>]/g,'').trim().slice(0,20)||'Jugador';try{localStorage.setItem('elBromasNick',n)}catch{}if(s?.connected)s.emit('player:name',n);players(window.__ebPlayers16||[])}
function addMsg(d){ui();const name=esc(d?.name||'Jugador'),text=esc(d?.text||'');if(!text)return;lastMsg=name+': '+String(d.text);$('ebChatLast16').textContent=lastMsg;const box=$('ebChatMsgs16');const row=document.createElement('div');row.style='padding:4px 2px;border-bottom:1px solid #293040;word-break:break-word';row.innerHTML='<b>'+name+':</b> '+text;box.appendChild(row);while(box.children.length>60)box.removeChild(box.firstChild);box.scrollTop=box.scrollHeight}
function sendChat(){const i=$('ebChatInput16');if(!i)return;const t=i.value.trim().slice(0,120);if(!t)return;if(s?.connected)s.emit('chat:send',t);i.value=''}
function start(){ui();if(!s){setTimeout(start,500);return}if(!s.__eb16){s.__eb16=1;window.__ebSelf16=s.id;s.on('connect',()=>{window.__ebSelf16=s.id;players(window.__ebPlayers16||[])});s.on('room:welcome',d=>{window.__ebSelf16=d?.id||s.id;players(d?.players||[])});s.on('room:sync',d=>players(d?.players||[]));s.on('room:players',a=>{window.__ebPlayers16=a||[];players(a)});s.on('online:count',n=>{ui();if(!$('ebConnNum16'))return;$('ebConnNum16').textContent=Math.max(0,Math.floor(Number(n)||0))});s.on('chat:message',addMsg);setInterval(()=>{if(!s.connected)return;const t=performance.now();s.emit('latency:ping',t,r=>{const x=Number(r?.echo);setPing(performance.now()-(Number.isFinite(x)?x:t))})},1000)} }
start()})();