(()=>{if(window.__EB_FX_READY)return;window.__EB_FX_READY=1;
try{if(typeof THREE!=='undefined'&&THREE.Object3D&&!THREE.Object3D.prototype.removeFromParent)THREE.Object3D.prototype.removeFromParent=function(){try{if(this.parent&&typeof this.parent.remove==='function')this.parent.remove(this)}catch(_){} }}catch(_){}
let sock=null,localVeh=null,remote=new Map(),lastFx='',nextPing=0,nextSend=0,baseEnter=null,baseExit=null,baseRadio=null;
const N=v=>Number.isFinite(+v)?+v:0;
const ready=()=>{try{return typeof scene!=='undefined'&&scene&&typeof scene.add==='function'}catch(_){return false}};
const waitReady=fn=>{if(ready())return fn();setTimeout(()=>waitReady(fn),50)};
const setPing=v=>{const e=document.getElementById('ebOnlinePing');if(e)e.textContent=Math.max(1,Math.round(N(v)||1))+' ms'};
function ping(){if(!sock?.connected)return;const t=Date.now();let done=false;const to=setTimeout(()=>{if(!done){done=true;setPing(1)}},2500);sock.emit('latency:ping',t,e=>{if(done)return;done=true;clearTimeout(to);setPing(Math.max(1,Date.now()-N(e||t)))})}
function delayedSocket(x){if(!x||x.__EB_SAFE_SOCKET)return x;x.__EB_SAFE_SOCKET=1;const on=x.on.bind(x);x.on=function(ev,fn){if(typeof fn!=='function')return on(ev,fn);if(ev==='vehicle:accepted')return x;if(ev==='room:welcome'||ev==='world:state'||ev==='effects:state'||ev==='vehicle:state'){return on(ev,function(...a){waitReady(()=>{try{fn.apply(this,a)}catch(_){}})})}return on(ev,fn)};return x}
const originalIO=window.io;if(typeof originalIO==='function'){window.io=function(){const x=delayedSocket(originalIO.apply(this,arguments));if(!sock){sock=x;bind()}return x}}
function bind(){if(!sock)return;const nativeOn=sock.on.bind(sock);nativeOn('connect',()=>{setPing(1);ping()});nativeOn('vehicle:accepted',v=>waitReady(()=>acceptVehicle(v)));nativeOn('vehicle:state',v=>waitReady(()=>handleCarState(v)));nativeOn('vehicle:radio',v=>waitReady(()=>handleCarState(v)));nativeOn('world:state',w=>waitReady(()=>{try{const c=w?.cars?.find(x=>x&&x.id===localVeh?.id);if(c&&localVeh){localVeh.station=N(c.station);try{carRadioStationIndex=N(c.station)}catch(_){}if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarRadio==='function')startCarRadio(false)}}catch(_) {}}));nativeOn('vehicle:left',()=>{localVeh=null;try{if(typeof stopCarRadio==='function')stopCarRadio(true)}catch(_){}try{if(typeof drivenCar!=='undefined')drivenCar=null;if(typeof isDriving!=='undefined')isDriving=false;if(typeof character!=='undefined')character.visible=true}catch(_){}restoreNormalHud()});nativeOn('disconnect',()=>setPing(1))}
function restoreNormalHud(){try{document.getElementById('carExitBtn')?.classList.remove('active');document.getElementById('carDrivingButtons')?.classList.remove('active');document.getElementById('carDriveHud')?.classList.remove('active');document.getElementById('carRadioPanel')?.classList.remove('active');document.getElementById('joystickArea')?.classList.remove('hidden');document.getElementById('actionButtons')?.classList.remove('hidden');if(typeof forceHudVisible==='function')forceHudVisible()}catch(_){} }
function hidePassengerHud(){try{document.getElementById('carExitBtn')?.classList.add('active');document.getElementById('carDrivingButtons')?.classList.remove('active');document.getElementById('carDriveHud')?.classList.remove('active');document.getElementById('carRadioPanel')?.classList.add('active');document.getElementById('joystickArea')?.classList.add('hidden');document.getElementById('actionButtons')?.classList.add('hidden')}catch(_){} }
function currentState(){try{if(!sock?.connected||!localVeh||typeof drivableCars==='undefined')return;const c=drivableCars[localVeh.id];if(!c)return;const d={name:(localStorage.getItem('elBromasNick')||'Jugador').slice(0,20),x:typeof character!=='undefined'?N(character.position.x):0,y:typeof character!=='undefined'?N(character.position.y):0,z:typeof character!=='undefined'?N(character.position.z):0,rx:typeof character!=='undefined'?N(character.rotation.x):0,ry:typeof character!=='undefined'?N(character.rotation.y):0,rz:typeof character!=='undefined'?N(character.rotation.z):0,hp:typeof playerHealth!=='undefined'?(N(playerHealth)||100):100,aura:typeof playerAura!=='undefined'?N(playerAura):0,kills:typeof totalPenesKilled!=='undefined'?N(totalPenesKilled):0,round:typeof waveNumber!=='undefined'?N(waveNumber):1,dead:typeof isDead!=='undefined'?!!isDead:false,vehicle:{id:localVeh.id,role:localVeh.role,station:N(typeof carRadioStationIndex!=='undefined'?carRadioStationIndex:localVeh.station)},car:{id:localVeh.id,x:N(c.position.x),y:N(c.position.y),z:N(c.position.z),ry:N(c.rotation.y),speed:N(c.userData?.speed),lights:!!c.userData?.lightsOn,station:N(typeof carRadioStationIndex!=='undefined'?carRadioStationIndex:localVeh.station)}};sock.emit('player:state',d)}catch(_){} }
function actualCar(){try{return localVeh&&typeof drivableCars!=='undefined'?drivableCars[localVeh.id]:null}catch(_){return null}}
function acceptVehicle(v){if(!v||typeof drivableCars==='undefined'||!drivableCars[v.id])return;const c=drivableCars[v.id];localVeh={id:N(v.id),role:v.role==='driver'?'driver':'passenger',station:N(v.station)};try{carRadioStationIndex=localVeh.station}catch(_){};
 if(localVeh.role==='driver'){try{if(baseEnter){drivenCar=c;isDriving=true;baseEnter()}else{drivenCar=c;isDriving=true;if(typeof character!=='undefined')character.visible=false}}catch(_){}try{drivenCar=c;isDriving=true;if(typeof character!=='undefined')character.visible=false;document.getElementById('carExitBtn')?.classList.add('active');document.getElementById('carDrivingButtons')?.classList.add('active');document.getElementById('carDriveHud')?.classList.add('active');document.getElementById('carRadioPanel')?.classList.add('active');document.getElementById('joystickArea')?.classList.add('hidden');document.getElementById('actionButtons')?.classList.add('hidden');if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarEngineSound==='function')startCarEngineSound();if(typeof startCarRadio==='function')startCarRadio(true);if(typeof forceHudVisible==='function')forceHudVisible()}catch(_) {}}else{try{drivenCar=c;isDriving=false;if(typeof character!=='undefined')character.visible=false;hidePassengerHud();if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarRadio==='function')startCarRadio(false)}catch(_){} }
 currentState()}
function handleCarState(v){try{if(!v||typeof drivableCars==='undefined'||!drivableCars[v.id])return;const c=drivableCars[v.id];c.userData.networkStation=N(v.station);if(!(localVeh&&localVeh.id===v.id&&localVeh.role==='driver')){c.position.set(N(v.x),N(v.y),N(v.z));c.rotation.y=N(v.ry);c.userData.speed=N(v.speed);c.userData.lightsOn=!!v.lights}if(localVeh&&localVeh.id===v.id){localVeh.station=N(v.station);try{carRadioStationIndex=N(v.station)}catch(_){}if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarRadio==='function')startCarRadio(false)}}catch(_){} }
function requestExit(){if(!localVeh||!sock?.connected)return false;const was=localVeh;localVeh=null;sock.emit('vehicle:exit');try{if(was.role==='driver'&&baseExit)baseExit();else{if(typeof drivenCar!=='undefined')drivenCar=null;if(typeof isDriving!=='undefined')isDriving=false;if(typeof character!=='undefined')character.visible=true;if(typeof stopCarRadio==='function')stopCarRadio(true);restoreNormalHud()}}catch(_){}return true}
function requestEnter(){try{if(!sock?.connected||typeof findNearestCar!=='function'||typeof drivableCars==='undefined')return baseEnter?baseEnter():undefined;const c=findNearestCar(8),i=drivableCars.indexOf(c);if(i>=0){sock.emit('vehicle:request',{id:i,station:N(c.userData?.networkStation)});return}return baseEnter?baseEnter():undefined}catch(_){return baseEnter?baseEnter():undefined}}
function radioChange(dir){try{if(!localVeh||!sock?.connected)return;if(baseRadio)baseRadio.call(this,dir);localVeh.station=N(typeof carRadioStationIndex!=='undefined'?carRadioStationIndex:localVeh.station);currentState()}catch(_){} }
function patchCars(){if(typeof enterNearestCar!=='function'||typeof exitDrivenCar!=='function')return;if(!baseEnter)baseEnter=enterNearestCar;if(!baseExit)baseExit=exitDrivenCar;if(!baseRadio&&typeof cycleCarRadio==='function')baseRadio=cycleCarRadio;window.enterNearestCar=requestEnter;window.exitDrivenCar=function(){if(requestExit())return;return baseExit.apply(this,arguments)};if(baseRadio)window.cycleCarRadio=radioChange}
function snap(){const projectiles=[],stains=[];try{if(typeof cacaProjectiles!=='undefined')cacaProjectiles.forEach((g,i)=>{if(!g?.position||g.userData?.__netRemote)return;const u=g.userData||{};u.__fxId=u.__fxId||('fx-'+(sock?.id||'me')+'-'+i+'-'+Math.random().toString(36).slice(2));if(projectiles.length<80)projectiles.push({id:u.__fxId,type:u.isMortero?'mortero':'diarrea',x:N(g.position.x),y:N(g.position.y),z:N(g.position.z),rx:N(g.rotation.x),ry:N(g.rotation.y),rz:N(g.rotation.z),size:N(u.size)||.4})});if(typeof cacaStains!=='undefined')cacaStains.forEach((g,i)=>{if(!g?.position||g.userData?.__netRemote)return;const u=g.userData||{};u.__fxId=u.__fxId||('st-'+(sock?.id||'me')+'-'+i+'-'+Math.random().toString(36).slice(2));if(stains.length<30)stains.push({id:u.__fxId,x:N(g.position.x),y:N(g.position.y),z:N(g.position.z),life:N(u.life),maxLife:N(u.maxLife)||3600,scale:N(g.scale?.x)||1})})}catch(_){}return{projectiles,stains}}
function sendFx(){if(!sock?.connected)return;const f=snap(),sig=JSON.stringify(f);if(sig===lastFx)return;lastFx=sig;sock.emit('effects:state',f)}
function removeMesh(g,arr){try{if(g?.parent&&typeof g.parent.remove==='function')g.parent.remove(g);if(Array.isArray(arr)){const i=arr.indexOf(g);if(i>=0)arr.splice(i,1)}}catch(_){} }
function makeProjectile(x){if(!ready()||typeof cacaProjectiles==='undefined'||typeof THREE==='undefined')return null;try{const geo=typeof _cacaGeo!=='undefined'?_cacaGeo:new THREE.SphereGeometry(.45,10,8);const mats=typeof _cacaColorsMats!=='undefined'&&Array.isArray(_cacaColorsMats)?_cacaColorsMats:[];const g=new THREE.Mesh(geo,mats[0]||new THREE.MeshLambertMaterial({color:0x6b3b16}));g.scale.setScalar(N(x.size)||.4);g.userData={__netRemote:true,__netFx:true,isMortero:x.type==='mortero',isDiarrea:x.type!=='mortero',isStatic:true,velocity:new THREE.Vector3(),gravity:0,life:999999,maxLife:999999,hasHit:true,hasLanded:true,bounces:0,size:N(x.size)||.4,damageRadius:0};g.position.set(N(x.x),N(x.y),N(x.z));g.rotation.set(N(x.rx),N(x.ry),N(x.rz));scene.add(g);cacaProjectiles.push(g);return g}catch(_){return null}}
function makeStain(x){if(!ready()||typeof createCacaStain!=='function'||typeof cacaStains==='undefined')return null;try{createCacaStain(N(x.x),N(x.z));const g=cacaStains[cacaStains.length-1];if(g){g.userData=g.userData||{};g.userData.__netRemote=true;g.userData.__netFx=true;g.userData.damageRadius=0;g.userData.__fxId=x.id;g.position.y=N(x.y)||g.position.y;return g}}catch(_){}return null}
function apply(f){if(!f||!f.owner||f.owner===sock?.id)return;const key=String(f.owner);let r=remote.get(key);if(!r){r={p:new Map(),s:new Map()};remote.set(key,r)}const pids=new Set((f.projectiles||[]).map(x=>x?.id).filter(Boolean));for(const x of f.projectiles||[]){if(!x?.id)continue;let g=r.p.get(x.id);if(!g)g=makeProjectile(x);if(!g)continue;g.userData.__fxTarget=x;g.position.x+=(N(x.x)-g.position.x)*.7;g.position.y+=(N(x.y)-g.position.y)*.7;g.position.z+=(N(x.z)-g.position.z)*.7;g.rotation.set(N(x.rx),N(x.ry),N(x.rz));g.scale.setScalar(N(x.size)||.4);r.p.set(x.id,g)}for(const[id,g]of r.p)if(!pids.has(id)){removeMesh(g,typeof cacaProjectiles==='undefined'?[]:cacaProjectiles);r.p.delete(id)}const sids=new Set((f.stains||[]).map(x=>x?.id).filter(Boolean));for(const x of f.stains||[]){if(!x?.id)continue;let g=r.s.get(x.id);if(!g)g=makeStain(x);if(!g)continue;g.userData.life=N(x.life);g.userData.maxLife=N(x.maxLife)||3600;g.position.set(N(x.x),N(x.y)||g.position.y,N(x.z));g.scale.setScalar(N(x.scale)||1);r.s.set(x.id,g)}for(const[id,g]of r.s)if(!sids.has(id)){removeMesh(g,typeof cacaStains==='undefined'?[]:cacaStains);r.s.delete(id)}}
function tick(t){if(t>=nextSend){nextSend=t+50;sendFx();if(localVeh)currentState()}if(t>=nextPing){nextPing=t+1000;ping()}patchCars();requestAnimationFrame(tick)}
window.addEventListener('beforeunload',()=>{try{if(sock?.connected){sock.emit('effects:state',{projectiles:[],stains:[]});if(localVeh)sock.emit('vehicle:exit')}}catch(_){} });setPing(1);requestAnimationFrame(tick);
})();