(()=>{if(window.__EB_ONLINE_CORE_V2)return;window.__EB_ONLINE_CORE_V2=1;
const N=(v,d=0)=>Number.isFinite(+v)?+v:d;
const nick=()=>{try{return(localStorage.getItem('elBromasNick')||'Jugador').trim().slice(0,20)||'Jugador'}catch{return'Jugador'}};
const saveNick=v=>{try{localStorage.setItem('elBromasNick',v)}catch{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let socket=null,selfId=null,players=[],remotes=new Map(),remoteNpcs=new Map(),remoteWorld=new Map();
let ui=null,isServerHost=true,isNpcSource=false,roleReady=false,lastSent=0,lastNpcSent=0,lastWorldSent=0,npcSeq=0,worldSeq=0,lastRound=-1,chatMessages=[],suppressNetwork=false;
function getSocket(){if(window.__ebSocket)return socket=window.__ebSocket;if(typeof io==='function')return socket=window.__ebSocket=io(location.origin,{path:'/socket.io',transports:['websocket','polling'],reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:300,timeout:10000});return null}
function pose(){const o={},u=typeof character!=='undefined'?(character?.userData||{}):{};['hips','torsoGroup','headGroup','leftShoulder','leftUpperArm','leftElbow','rightShoulder','rightUpperArm','rightElbow','nalgasGroup','leftThigh','leftKnee','rightThigh','rightKnee','tuboGroup'].forEach(k=>{const r=u[k]?.rotation;if(r)o[k]=[r.x,r.y,r.z]});return o}
function state(){if(typeof character==='undefined'||!character?.position)return null;return{name:nick(),x:N(character.position.x),y:N(character.position.y),z:N(character.position.z),rx:N(character.rotation?.x),ry:N(character.rotation?.y),rz:N(character.rotation?.z),hp:N(typeof playerHealth!=='undefined'?playerHealth:100,100),aura:N(typeof playerAura!=='undefined'?playerAura:0),kills:N(typeof totalPenesKilled!=='undefined'?totalPenesKilled:0),dead:!!(typeof isDead!=='undefined'&&isDead),moving:!!(typeof isMoving!=='undefined'&&isMoving),running:!!(typeof isRunning!=='undefined'&&isRunning),jumping:!!(typeof isJumping!=='undefined'&&isJumping),flying:!!(typeof isFlying!=='undefined'&&isFlying),attacking:!!(typeof isAttacking!=='undefined'&&isAttacking),special:!!(typeof isSpecialAttacking!=='undefined'&&isSpecialAttacking),attackPhase:N(typeof attackPhase!=='undefined'?attackPhase:0),specialPhase:N(typeof specialPhase!=='undefined'?specialPhase:0),walkCycle:N(typeof walkCycle!=='undefined'?walkCycle:0),round:N(typeof waveNumber!=='undefined'?waveNumber:0),pose:pose()}}
function findFace(root){let f=root?.userData?.face||null;if(f)return f;try{root?.traverse?.(o=>{if(f||!o?.isMesh)return;const n=String(o.name||'').toLowerCase();if(n.includes('face')||n.includes('cara'))f=o})}catch{}return f}
function copyFace(src,dst){if(!src||!dst||typeof THREE==='undefined')return;try{const sf=findFace(src),df=findFace(dst);if(sf?.material&&df){df.material=sf.material.clone?sf.material.clone():sf.material;if(sf.material.map)df.material.map=sf.material.map}}catch{}}
function label(r,name){if(!r?.g||r.name===name&&r.label)return;r.name=name||'Jugador';r.label?.parent?.remove(r.label);if(typeof THREE==='undefined')return;const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d');x.font='bold 42px Arial';x.textAlign='center';x.textBaseline='middle';x.lineWidth=8;x.strokeStyle='rgba(0,0,0,.85)';x.strokeText(r.name,256,48);x.fillStyle='#fff';x.fillText(r.name,256,48);const t=new THREE.CanvasTexture(c),s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(2.7,.5,1);s.position.y=2.8;r.label=s;r.g.add(s)}
function addRemote(p){if(!p?.id||p.id===selfId||remotes.has(p.id)||typeof scene==='undefined'||typeof createCharacterWithSkeleton!=='function')return;try{const g=createCharacterWithSkeleton();if(!g)return;g.userData=g.userData||{};g.userData.__ebRemote=true;g.userData.__ebRemoteId=p.id;scene.add(g);const r={g,name:'',target:new THREE.Vector3(N(p.x),N(p.y),N(p.z))};remotes.set(p.id,r);label(r,p.name);copyFace(typeof character!=='undefined'?character:null,g);applyPlayer(r,p)}catch(e){console.warn('remote player',e)}}
function removeRemote(id){const r=remotes.get(id);if(r){r.g?.parent?.remove(r.g);remotes.delete(id)}}
function applyPlayer(r,p){if(!r?.g)return;r.target.set(N(p.x),N(p.y),N(p.z));r.g.rotation.set(N(p.rx),N(p.ry),N(p.rz));r.g.visible=!p.dead;label(r,p.name);copyFace(typeof character!=='undefined'?character:null,r.g);for(const[k,v]of Object.entries(p.pose||{}))if(r.g.userData[k]?.rotation)r.g.userData[k].rotation.set(N(v[0]),N(v[1]),N(v[2]));const u=r.g.userData||{};u.netMoving=!!p.moving;u.netRunning=!!p.running;u.netJumping=!!p.jumping;u.netFlying=!!p.flying;u.netAttacking=!!p.attacking;u.netSpecial=!!p.special;u.netWalkCycle=N(p.walkCycle);u.netAttackPhase=N(p.attackPhase);u.netSpecialPhase=N(p.specialPhase)}
function draw(){if(!ui)return;ui.list.innerHTML='<div class="ebTitle"><b>Conectados '+players.length+'</b><button id="ebNickBtn">✏️</button></div>'+players.map(p=>'<div class="ebRow '+(p.id===selfId?'me':'')+'"><b>'+esc(p.name||'Jugador')+(p.id===selfId?' ⭐':'')+'</b><span>❤️ '+Math.round(N(p.hp,100))+'</span><span>🌀 '+Math.round(N(p.aura))+'</span><span>☠ '+Math.round(N(p.kills))+'</span></div>').join('');const b=ui.list.querySelector('#ebNickBtn');if(b)b.onclick=rename;ui.count.textContent='Conectados '+players.length}
function rename(){document.getElementById('ebNameBox')?.remove();const box=document.createElement('div');box.id='ebNameBox';box.innerHTML='<div>Nombre</div><input id="ebNameInput" maxlength="20"><button id="ebNameSave">Guardar</button>';document.body.appendChild(box);const i=box.querySelector('#ebNameInput');i.value=nick();i.focus();box.querySelector('#ebNameSave').onclick=()=>{const n=(i.value||'').replace(/[<>]/g,'').trim().slice(0,20)||'Jugador';saveNick(n);socket?.emit('player:name',n);box.remove()}}
function openChat(){ui.chat.style.display=ui.chat.style.display==='none'?'block':'none'}
function sendChat(){const i=ui.chat.querySelector('#ebChatInput'),v=i.value.trim();if(v&&socket?.connected){socket.emit('chat:send',v);i.value=''}}
function renderChat(){const l=ui.chat.querySelector('#ebChatLog');l.innerHTML=chatMessages.map(m=>'<div><b>'+esc(m.name)+'</b>: '+esc(m.text)+'</div>').join('');l.scrollTop=l.scrollHeight}
function hideRestart(){const apply=()=>document.querySelectorAll('button,[role="button"],input[type="button"],input[type="submit"]').forEach(e=>{if((e.textContent||e.value||'').trim().toLowerCase().includes('reiniciar mundo')){e.style.setProperty('display','none','important');e.setAttribute('aria-hidden','true')}});apply();new MutationObserver(apply).observe(document.body,{childList:true,subtree:true})}
function renameCarButton(){document.querySelectorAll('button,[role="button"],input[type="button"],input[type="submit"]').forEach(e=>{const raw=(e.textContent||e.value||'').trim().toLowerCase();if(/entrar\s+(al|a)\s+(carro|coche|veh[ií]culo)|subir\s+al\s+(carro|coche|veh[ií]culo)/i.test(raw)){if('value'in e)e.value='Manejar';else e.textContent='Manejar'}})}
function build(){if(document.getElementById('ebCoreHud'))return;const st=document.createElement('style');st.textContent='#ebCoreHud{position:fixed;left:50%;bottom:14px;transform:translateX(-50%);z-index:2147483000;font:900 13px Arial;white-space:nowrap}#ebCoreHud button{border:1px solid #7280ff;border-radius:20px;background:#0c0f18ee;color:#fff;padding:9px 15px}#ebPing{position:fixed;top:12px;right:14px;z-index:2147483002;border:1px solid #40c9ff;border-radius:14px;background:#07101bf2;color:#fff;padding:7px 11px;font:900 12px Arial}#ebChatBtn{margin-left:7px}#ebCoreList,#ebChat{display:none;position:fixed;left:50%;bottom:58px;transform:translateX(-50%);width:min(430px,94vw);max-height:46vh;overflow:auto;z-index:2147482999;background:#080c15fa;color:#fff;border:1px solid #7280ff;border-radius:16px;padding:10px;box-sizing:border-box;font:12px Arial}.ebTitle{display:flex;justify-content:space-between;padding-bottom:6px}.ebRow{display:grid;grid-template-columns:1fr auto auto auto;gap:7px;padding:9px;border-bottom:1px solid #293040}.ebRow.me{background:#5064ff2b;border-radius:8px}#ebNickBtn{border:0;background:transparent;color:#fff;font-size:17px}#ebNameBox{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2147483647;background:#111827;color:#fff;border:1px solid #7280ff;border-radius:12px;padding:16px;min-width:210px;font:16px Arial}#ebNameInput{display:block;width:100%;box-sizing:border-box;margin:10px 0;padding:8px}#ebNameSave{width:100%;padding:8px}#ebChatLog{height:180px;overflow:auto;margin-bottom:8px}#ebChatInput{width:calc(100% - 70px);box-sizing:border-box;padding:8px}#ebChatSend{width:60px;padding:8px}';document.head.appendChild(st);const h=document.createElement('div');h.id='ebCoreHud';h.innerHTML='<button id="ebCoreBtn">Conectados 0</button><button id="ebChatBtn">Chat</button><div id="ebCoreList"></div><div id="ebChat"><div id="ebChatLog"></div><input id="ebChatInput" maxlength="120"><button id="ebChatSend">Enviar</button></div>';document.body.appendChild(h);const ping=document.createElement('div');ping.id='ebPing';ping.textContent='-- ms';document.body.appendChild(ping);ui={count:h.querySelector('#ebCoreBtn'),list:h.querySelector('#ebCoreList'),chat:h.querySelector('#ebChat'),ping};h.querySelector('#ebCoreBtn').onclick=()=>{ui.list.style.display=getComputedStyle(ui.list).display==='none'?'block':'none';draw()};h.querySelector('#ebChatBtn').onclick=openChat;h.querySelector('#ebChatSend').onclick=sendChat;h.querySelector('#ebChatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()};hideRestart();renameCarButton()}
function removeLocalNpcs(){try{if(Array.isArray(smallPenes)){smallPenes.forEach(o=>o?.parent&&scene.remove(o));smallPenes.length=0}if(Array.isArray(activeMiniBosses)){activeMiniBosses.forEach(o=>o?.parent&&scene.remove(o));activeMiniBosses.length=0}if(typeof cinematicBosses!=='undefined'&&Array.isArray(cinematicBosses)){cinematicBosses.forEach(o=>o?.parent&&scene.remove(o));cinematicBosses.length=0}if(typeof boss!=='undefined'&&boss){boss.parent&&scene.remove(boss);boss=null}}catch{}}
let patches=null;
function applyAuthority(){const shouldSuppress=roleReady&&!isNpcSource;if(shouldSuppress&&!patches){patches={};['spawnWave','startWaves','spawnNextWave','startProtestMission','startGiantBossMission'].forEach(k=>{if(typeof window[k]==='function'){patches[k]=window[k];window[k]=()=>{}}});removeLocalNpcs()}else if(!shouldSuppress&&patches){Object.keys(patches).forEach(k=>window[k]=patches[k]);patches=null}}
function ensureNpcId(o,type){if(!o?.userData)return null;if(!o.userData.__ebNpcId)o.userData.__ebNpcId=type+'-'+(++npcSeq);return o.userData.__ebNpcId}
function npcState(o,type){const u=o.userData||{};return{id:ensureNpcId(o,type),type,x:N(o.position?.x),y:N(o.position?.y),z:N(o.position?.z),rx:N(o.rotation?.x),ry:N(o.rotation?.y),rz:N(o.rotation?.z),hp:Math.max(0,N(u.health,0)),maxHp:Math.max(1,N(u.maxHealth,100)),walkCycle:N(u.walkCycle),attacking:!!(u.isCharging||u.isAttacking),isGiant:!!u.isGiant,isProtester:!!u.isProtester,leap:!!u.isLeaping,leapPhase:N(u.leapPhase),flyTimer:N(u.flyTimer)}}
function collectNpcSnapshot(){const items=[];try{if(Array.isArray(smallPenes))for(const o of smallPenes)if(o?.parent&&o.userData?.health>0)items.push(npcState(o,'pene'));if(Array.isArray(activeMiniBosses))for(const o of activeMiniBosses)if(o?.parent&&o.userData?.health>0)items.push(npcState(o,'miniBoss'));if(typeof boss!=='undefined'&&boss?.parent&&boss.userData?.health>0)items.push(npcState(boss,'boss'))}catch{}return{round:N(typeof waveNumber!=='undefined'?waveNumber:lastRound),items}}
function makeRemoteNpc(p){if(!p?.id||typeof scene==='undefined'||typeof THREE==='undefined')return null;let g=null;try{if(p.type==='pene'){if(p.isProtester&&typeof createProtesterPene==='function'&&typeof posterTextureObj!=='undefined'&&posterTextureObj)g=createProtesterPene(p.x,p.z,posterTextureObj);else if(typeof createSmallPene==='function')g=createSmallPene(p.x,p.z)}else if((p.type==='boss'||p.type==='miniBoss')&&typeof createBoss==='function'){g=createBoss(Math.max(0,N(p.round,lastRound)));const sc=p.type==='boss'?3:1.2;g.scale.set(sc,sc,sc)}if(!g)return null;g.userData=g.userData||{};g.userData.__ebRemoteNpc=true;g.userData.__ebNpcId=p.id;g.userData.health=N(p.hp);g.userData.maxHealth=N(p.maxHp,100);scene.add(g);return{g,type:p.type,target:new THREE.Vector3(N(p.x),N(p.y),N(p.z))}}catch(e){console.warn('remote npc',e);return null}}
function applyRemoteNpcPose(r,p){if(!r?.g)return;r.target.set(N(p.x),N(p.y),N(p.z));r.g.rotation.set(N(p.rx),N(p.ry),N(p.rz));r.g.userData.health=N(p.hp,r.g.userData.health);r.g.userData.netMoving=true;r.g.userData.netAttacking=!!p.attacking;r.g.userData.netWalkCycle=N(p.walkCycle);r.g.userData.netLeap=!!p.leap;r.g.userData.netLeapPhase=N(p.leapPhase);r.g.userData.netFlyTimer=N(p.flyTimer)}
function applyNpcSnapshot(msg){if(isNpcSource)return;const pld=msg&&typeof msg==='object'&&!Array.isArray(msg)?msg:{items:Array.isArray(msg)?msg:[]};if(pld.round!=null)lastRound=N(pld.round,lastRound);const seen=new Set;for(const p of pld.items||[]){if(!p?.id)continue;seen.add(p.id);let r=remoteNpcs.get(p.id);if(!r){r=makeRemoteNpc(p);if(r)remoteNpcs.set(p.id,r)}if(r)applyRemoteNpcPose(r,p)}for(const[id,r]of remoteNpcs)if(!seen.has(id)){r.g?.parent?.remove(r.g);remoteNpcs.delete(id)}}
function genericWorldObjects(){const out=[];if(typeof scene==='undefined'||!scene?.traverse)return out;scene.traverse(o=>{if(!o?.isObject3D||o.userData?.__ebRemoteWorld)return;const u=o.userData||{},n=String(o.name||'').toLowerCase(),sem=String(u.type||u.kind||u.category||'').toLowerCase();if(/projectile|proyectil|mortar|mortero|diarrea|attack|ataque|explosion|explosión|mancha|splat|impact|impacto|effect|efecto|cinematic|cinematica|cinemática|carro|coche|vehiculo|vehículo|vehicle|car/.test(n+' '+sem)){const id=u.__ebWorldId||(u.__ebWorldId='w-'+(++worldSeq));out.push({id,type:sem||n||'world',name:String(o.name||'').slice(0,60),x:N(o.position?.x),y:N(o.position?.y),z:N(o.position?.z),rx:N(o.rotation?.x),ry:N(o.rotation?.y),rz:N(o.rotation?.z),sx:N(o.scale?.x,1),sy:N(o.scale?.y,1),sz:N(o.scale?.z,1),visible:o.visible!==false,life:N(u.life,u.ttl),state:N(u.state,u.phase),active:!!u.active||o.visible!==false,car:/carro|coche|vehiculo|vehículo|vehicle|car/.test(n+' '+sem)})}});return out.slice(0,160)}
function templateForRemote(id){return scene?.getObjectByProperty?.('userData.__ebWorldId',id)||null}
function makeRemoteWorld(w){if(typeof THREE==='undefined'||typeof scene==='undefined')return null;let g=null;try{const src=templateForRemote(w.id);if(src){g=src.clone(true);g.userData=Object.assign({},g.userData,{__ebRemoteWorld:true,__ebWorldId:w.id});scene.add(g)}else if(w.car&&typeof createCar==='function'){try{g=createCar();g.userData=Object.assign({},g.userData,{__ebRemoteWorld:true,__ebWorldId:w.id});scene.add(g)}catch{}}if(!g)return null;return{g,target:new THREE.Vector3(w.x,w.y,w.z)}}catch{return null}}
function applyWorldSnapshot(items){const seen=new Set;for(const w of items||[]){if(!w?.id)continue;seen.add(w.id);let r=remoteWorld.get(w.id);if(!r){r=makeRemoteWorld(w);if(r)remoteWorld.set(w.id,r)}if(!r)continue;r.target.set(N(w.x),N(w.y),N(w.z));r.g.rotation.set(N(w.rx),N(w.ry),N(w.rz));r.g.scale.set(N(w.sx,1),N(w.sy,1),N(w.sz,1));r.g.visible=w.visible!==false}for(const[id,r]of remoteWorld)if(!seen.has(id)){r.g?.parent?.remove(r.g);remoteWorld.delete(id)}}
function serializeArg(v){if(v==null||typeof v==='string'||typeof v==='number'||typeof v==='boolean')return v;if(Array.isArray(v))return v.slice(0,12).map(serializeArg);if(typeof v==='object'){if(typeof v.x==='number'&&typeof v.y==='number'&&typeof v.z==='number')return{x:v.x,y:v.y,z:v.z};const o={};for(const k of Object.keys(v).slice(0,8))if(['string','number','boolean'].includes(typeof v[k]))o[k]=v[k];return o}return null}
const actionNames=['mortarAttack','doMortarAttack','spawnMortar','launchMortar','fireMortar','diarreaAttack','attackDiarrea','doDiarreaAttack','spawnProjectile','createProjectile','launchProjectile','explode','createExplosion','showImpact','createImpact','spawnAttackMark','createAttackMark','startCinematic','playCinematic','startCinematica'];
function syncInteractions(){if(!socket?.connected||suppressNetwork)return;for(const name of actionNames){const fn=window[name];if(typeof fn!=='function'||fn.__ebWrapped)continue;const wrapped=function(...args){const out=fn.apply(this,args);try{socket.emit('action:event',{name,args:args.map(serializeArg).slice(0,8)})}catch{}return out};wrapped.__ebWrapped=true;wrapped.__ebOriginal=fn;window[name]=wrapped}}
function playRemoteAction(d){if(!d?.name||typeof window[d.name]!=='function')return;suppressNetwork=true;try{window[d.name](...(d.args||[]))}catch{}suppressNetwork=false}
function start(){if(!document.body)return;build();socket=getSocket();if(!socket){setTimeout(start,500);return}socket.on('connect',()=>{selfId=socket.id;socket.emit('room:join',{name:nick(),round:N(typeof waveNumber!=='undefined'?waveNumber:0)})});socket.on('room:welcome',d=>{selfId=d.id||socket.id;players=Array.isArray(d.players)?d.players:[];lastRound=N(d.round,lastRound);isServerHost=!!d.serverHost;isNpcSource=!!d.npcSource;roleReady=true;draw();applyAuthority();applyNpcSnapshot(d.npcSnapshot);applyWorldSnapshot(d.worldSnapshot?.items||[])});socket.on('room:role',d=>{isServerHost=!!d?.serverHost;isNpcSource=!!d?.npcSource;roleReady=true;applyAuthority()});socket.on('room:players',ps=>{players=Array.isArray(ps)?ps:[];for(const p of players)if(p.id!==selfId)addRemote(p);for(const[id]of remotes)if(!players.some(p=>p.id===id))removeRemote(id);draw()});socket.on('round:state',r=>{lastRound=N(r,lastRound);try{if(typeof waveNumber!=='undefined')waveNumber=lastRound}catch{}});socket.on('npc:snapshot',applyNpcSnapshot);socket.on('world:snapshot',d=>{if(!isNpcSource)applyWorldSnapshot(d?.items||[])});socket.on('action:event',playRemoteAction);socket.on('chat:message',m=>{chatMessages.push(m);chatMessages=chatMessages.slice(-50);renderChat()});socket.on('disconnect',()=>{if(ui)ui.ping.textContent='-- ms'});setInterval(()=>{if(!socket?.connected)return;const t=performance.now();socket.emit('latency:ping',t,r=>{if(ui)ui.ping.textContent=Math.max(1,Math.round(performance.now()-(r?.echo||t)))+' ms'})},2000);requestAnimationFrame(tick)}
function tick(){try{renameCarButton();syncInteractions();for(const [,r]of remotes)r.g.position.lerp(r.target,.38);for(const r of remoteNpcs.values())r.g.position.lerp(r.target,.42);for(const r of remoteWorld.values())r.g.position.lerp(r.target,.5);const now=performance.now();if(socket?.connected){if(now-lastSent>50){const s=state();if(s){socket.emit('player:state',s);lastSent=now}}if(isNpcSource&&now-lastNpcSent>33){const n=collectNpcSnapshot();socket.emit('npc:snapshot',n);if(n.round!==lastRound)socket.emit('round:set',n.round);lastNpcSent=now}if(isNpcSource&&now-lastWorldSent>66){socket.emit('world:snapshot',{items:genericWorldObjects(),round:lastRound});lastWorldSent=now}}}catch{}requestAnimationFrame(tick)}
function boot(){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else setTimeout(start,0)}boot()})()
