(()=>{if(window.__EB_NET15)return;window.__EB_NET15=1;const s=window.__ebSocket;let pingBox=null,playersBox=null,listBox=null,open=false;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function ui(){if(!pingBox){pingBox=$('ebPing');if(!pingBox){pingBox=document.createElement('div');pingBox.id='ebPing';pingBox.style='position:fixed;top:10px;right:10px;z-index:2147483647;background:#07101bf2;border:1px solid #40c9ff;border-radius:12px;padding:6px 10px;font:bold 12px Arial;';document.body.appendChild(pingBox)}pingBox.textContent='-- ms'}if(!playersBox){playersBox=document.createElement('div');playersBox.id='ebPlayers';playersBox.style='position:fixed;top:48px;right:10px;z-index:2147483647;background:#07101bf2;color:#fff;border:1px solid #40c9ff;border-radius:12px;padding:0;font:bold 12px Arial;min-width:230px;max-width:min(360px,90vw);overflow:hidden;';const h=document.createElement('div');h.id='ebPlayersHead';h.style='display:flex;align-items:center;gap:8px;padding:8px 10px;cursor:pointer;user-select:none;';h.innerHTML='<span id="ebPlayersTitle" style="flex:1">👥 Conectados: 0</span><button id="ebNameEdit" type="button" title="Cambiar nombre" style="width:32px;height:32px;border-radius:8px;background:#202942;color:#fff;border:1px solid #7280ff;font-size:17px">✏️</button>';listBox=document.createElement('div');listBox.id='ebPlayersList';listBox.style='display:none;max-height:45vh;overflow:auto;border-top:1px solid #293040;';playersBox.append(h,listBox);document.body.appendChild(playersBox);h.onclick=e=>{if(e.target?.id==='ebNameEdit')return;open=!open;listBox.style.display=open?'block':'none'};$('ebNameEdit').onclick=rename}}
function pingColor(ms){if(ms<=45)return'#b8ffb8';if(ms<=80)return'#72ff72';if(ms<=130)return'#cfff45';if(ms<=200)return'#ffe23b';if(ms<=300)return'#ff9d32';return'#ff3b3b'}
function setPing(ms){ui();ms=Math.max(0,Math.min(999,Math.round(Number(ms)||0)));const c=pingColor(ms);pingBox.textContent=ms+' ms';pingBox.style.color=c;pingBox.style.borderColor=c;pingBox.dataset.ms=String(ms)}
function sanitizePing(){ui();const t=pingBox.textContent||'';const m=t.match(/(\d+(?:\.\d+)?)/);if(m)setPing(m[1])}
function setPlayers(a){window.__ebPlayers=Array.isArray(a)?a:[];ui();const list=window.__ebPlayers;const n=list.length;$('ebPlayersTitle').textContent='👥 Conectados: '+n;listBox.innerHTML=list.map(x=>'<div style="display:grid;grid-template-columns:minmax(90px,1fr) auto auto auto;gap:7px;align-items:center;padding:9px 10px;border-bottom:1px solid #293040"><b>'+esc(x.name||'Jugador')+(x.id===window.__ebPlayerId?' ⭐':'')+'</b><span title="Vida">❤️ '+Math.round(Number(x.hp)||100)+'</span><span title="Aura">🌀 '+Math.round(Number(x.aura)||0)+'</span><span title="Bajas">☠ '+Math.round(Number(x.kills)||0)+'</span></div>').join('')}
function rename(e){e?.stopPropagation?.();const old=localStorage.getItem('elBromasNick')||'Jugador';const n=prompt('Cambiar nombre',old);if(n===null)return;const name=String(n).replace(/[<>]/g,'').trim().slice(0,20)||'Jugador';try{localStorage.setItem('elBromasNick',name)}catch{}if(s?.connected)s.emit('player:name',name);const a=window.__ebPlayers||[];for(const p of a)if(p.id===window.__ebPlayerId)p.name=name;setPlayers(a)}
function install(){ui();if(!s||s.__ebPing15)return;s.__ebPing15=1;s.on('latency:server',x=>{if(Number.isFinite(+x))setPing(x)});s.on('online:count',n=>{if(Array.isArray(window.__ebPlayers)&&window.__ebPlayers.length!==n&&n===1)setPlayers(window.__ebPlayers)});s.on('room:players',a=>{window.__ebPlayerId=s.id;setPlayers(a)});s.on('room:welcome',d=>{window.__ebPlayerId=d?.id||s.id;setPlayers(d?.players||[])});s.on('room:sync',d=>setPlayers(d?.players||[]));s.on('connect',()=>{window.__ebPlayerId=s.id;setPlayers(window.__ebPlayers||[])});setInterval(()=>{if(!s.connected)return;const t=performance.now();s.emit('latency:ping',t,r=>{const ms=performance.now()-Number(r?.echo||t);setPing(ms)})},1000);const obs=new MutationObserver(sanitizePing);obs.observe(pingBox,{childList:true,characterData:true,subtree:true});setInterval(sanitizePing,120)}
function car(){if(window.__EB_CAR15)return;window.__EB_CAR15=1;const orig=window.__EB_ENTER_ORIG14||window.enterNearestCar;if(typeof orig!=='function')return;window.__EB_ENTER_ORIG15=orig;window.enterNearestCar=function(){let i=-1,bd=64;try{if(Array.isArray(drivableCars)&&typeof character!=='undefined')for(let j=0;j<drivableCars.length;j++){const c=drivableCars[j];if(!c?.parent)continue;const dx=character.position.x-c.position.x,dz=character.position.z-c.position.z,d=dx*dx+dz*dz;if(d<bd){bd=d;i=j}}}catch{}if(i<0)return orig();try{const busy=(Array.isArray(window.__ebNetPlayers)?window.__ebNetPlayers:[]).some(p=>p.id!==window.__ebNetSelf&&p.driving&&p.carIndex===i);if(busy)return;}catch{}orig();if(s?.connected)s.emit('car:claim',i)};s?.on('room:players',a=>{window.__ebNetPlayers=a||[];window.__ebPlayerId=s.id});s?.on('room:welcome',d=>{window.__ebNetSelf=d?.id;window.__ebNetPlayers=d?.players||[]});s?.on('room:sync',d=>{window.__ebNetPlayers=d?.players||[]});s?.on('car:claim:deny',()=>{try{if(typeof exitDrivenCar==='function')exitDrivenCar()}catch{}})}
function start(){ui();install();car();setTimeout(start,5000)}start()})();
