(()=>{if(window.__EB_FIXES_READY)return;window.__EB_FIXES_READY=1;const N=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};let localVehicle=null,worldState=null,unread=0;const sock=()=>window.__ebSocket&&window.__ebSocket.connected?window.__ebSocket:null;const el=id=>document.getElementById(id);
function hudDriver(){try{const c=drivableCars?.[localVehicle.id];if(!c)return;drivenCar=c;isDriving=true;if(typeof character!=='undefined'){character.position.copy(c.position);character.position.y=c.position.y;character.visible=false}el('carExitBtn')?.classList.add('active');el('carDrivingButtons')?.classList.add('active');el('carDriveHud')?.classList.add('active');el('carRadioPanel')?.classList.add('active');if(typeof joystickArea!=='undefined'&&joystickArea)joystickArea.style.display='none';if(typeof actionButtons!=='undefined'&&actionButtons)actionButtons.style.display='none';if(typeof carInput!=='undefined')carInput={steer:0,throttle:0,reverse:0};if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarEngineSound==='function')startCarEngineSound();if(typeof startCarRadio==='function')startCarRadio(true);if(typeof forceHudVisible==='function')forceHudVisible()}catch(e){console.warn('car driver hud',e)}}
function hudPassenger(){try{const c=drivableCars?.[localVehicle.id];if(c){drivenCar=c;c.userData.speed=c.userData.speed||0;if(typeof character!=='undefined'){character.position.copy(c.position);character.position.y=c.position.y;character.visible=false}}isDriving=false;el('carExitBtn')?.classList.add('active');el('carDrivingButtons')?.classList.remove('active');el('carDriveHud')?.classList.remove('active');el('carRadioPanel')?.classList.add('active');if(typeof joystickArea!=='undefined'&&joystickArea)joystickArea.style.display='none';if(typeof actionButtons!=='undefined'&&actionButtons)actionButtons.style.display='none';if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarRadio==='function')startCarRadio(false)}catch(e){console.warn('car passenger hud',e)}}
function leaveVehicle(){try{if(typeof stopCarRadio==='function')stopCarRadio(true);if(typeof stopCarEngineSound==='function')stopCarEngineSound()}catch(_){}localVehicle=null;try{drivenCar=null;isDriving=false;if(typeof character!=='undefined')character.visible=true;el('carExitBtn')?.classList.remove('active');el('carDrivingButtons')?.classList.remove('active');el('carDriveHud')?.classList.remove('active');el('carRadioPanel')?.classList.remove('active');if(typeof joystickArea!=='undefined'&&joystickArea)joystickArea.style.display='block';if(typeof actionButtons!=='undefined'&&actionButtons)actionButtons.style.display='flex';if(typeof forceHudVisible==='function')forceHudVisible()}catch(_) {}}
function vehicleAccepted(v){if(!v||typeof drivableCars==='undefined'||!drivableCars?.[v.id])return;localVehicle={id:N(v.id),role:v.role==='driver'?'driver':'passenger',station:N(v.station)};try{carRadioStationIndex=localVehicle.station}catch(_){}if(localVehicle.role==='driver')hudDriver();else hudPassenger()}
function vehicleState(v){if(!v)return;const c=drivableCars?.[v.id];if(c){c.userData.networkStation=N(v.station);if(!(localVehicle&&localVehicle.id===v.id&&localVehicle.role==='driver')){c.position.set(N(v.x),N(v.y),N(v.z));c.rotation.y=N(v.ry);c.userData.speed=N(v.speed);c.userData.lightsOn=!!v.lights}}if(localVehicle&&localVehicle.id===v.id){localVehicle.station=N(v.station);try{carRadioStationIndex=N(v.station)}catch(_){}if(typeof updateCarRadioUI==='function')updateCarRadioUI();if(typeof startCarRadio==='function')startCarRadio(false)}}
function requestCar(){try{if(!sock()||typeof findNearestCar!=='function')return;const c=findNearestCar(8);if(!c)return;const id=drivableCars.indexOf(c);if(id<0)return;sock().emit('vehicle:request',{id,station:N(c.userData?.networkStation)});return}catch(_){}return null}
function carHint(){try{const h=el('carEnterHint');if(!h||typeof isDriving!=='undefined'&&isDriving)return;const c=typeof findNearestCar==='function'?findNearestCar(8):null;if(!c){h.classList.remove('active');return}const id=drivableCars.indexOf(c),v=worldState?.cars?.find(x=>x.id===id);h.textContent=v?.driver?'🚗 ENTRAR':'🚗 CONDUCIR';h.classList.add('active')}catch(_) {}}
function patchEnter(){if(window.__EB_FIX_ENTER)return;window.__EB_FIX_ENTER=1;const old=window.enterNearestCar;window.enterNearestCar=function(){requestCar()||((typeof old==='function')&&old.apply(this,arguments))};const oldExit=window.exitDrivenCar;window.exitDrivenCar=function(){if(localVehicle&&sock()){sock().emit('vehicle:exit');return}return typeof oldExit==='function'?oldExit.apply(this,arguments):undefined};}
function chatUI(){if(el('ebChatUnread'))return;const b=el('ebChatButton');if(!b)return;b.textContent='💬';b.setAttribute('aria-label','Chat');const badge=document.createElement('span');badge.id='ebChatUnread';badge.textContent='0';badge.style.cssText='position:absolute;right:-5px;top:-6px;min-width:17px;height:17px;padding:0 4px;border-radius:10px;background:#ff3b55;color:#fff;font:900 10px/17px Arial;text-align:center;box-sizing:border-box;display:none';b.style.position='fixed';b.appendChild(badge);const st=document.createElement('style');st.textContent='#ebChatPanel{overflow:hidden}#ebChatLog{overflow-x:hidden;overflow-y:auto;word-break:break-word;overflow-wrap:anywhere;white-space:normal}#ebChatLog div{max-width:100%;overflow-wrap:anywhere;word-break:break-word;margin:4px 0;line-height:1.35}';document.head.appendChild(st);b.onclick=()=>{const p=el('ebChatPanel');const open=p&&getComputedStyle(p).display!=='none';if(!open){unread=0;badge.textContent='0';badge.style.display='none';setTimeout(()=>el('ebChatInput')?.focus(),50)}if(p)p.style.display=open?'none':'block';if(typeof drawChat==='function')drawChat()}}
function unreadMessage(){unread++;const b=el('ebChatUnread');if(!b)return;b.textContent=unread>99?'99+':String(unread);b.style.display='block'}
function bind(){const s=sock();if(!s||s.__EB_FIX_BOUND)return false;s.__EB_FIX_BOUND=1;s.on('vehicle:accepted',vehicleAccepted);s.on('vehicle:state',vehicleState);s.on('vehicle:radio',vehicleState);s.on('vehicle:left',leaveVehicle);s.on('world:state',w=>{worldState=w});s.on('chat:message',()=>{const p=el('ebChatPanel');if(!p||getComputedStyle(p).display==='none')unreadMessage()});return true}
function loop(){chatUI();patchEnter();bind();carHint();requestAnimationFrame(loop)}loop();})();