// Bootstrap wrapper: authoritative NPC timer, persistent cars/radio/world structures and shared day/night clock.
const fs=require('fs');
const original=fs.readFileSync;
fs.readFileSync=function(file,enc){
  const out=original.apply(this,arguments),name=String(file);
  if(typeof out==='string'&&/server-base\.js$/.test(name)){
    let x=out;
    x=x.replace(/let npcSnapshot=\{seq:0,serverTime:0,round:0,items:\[\]\},worldSnapshot=/,
      "let idleNpcTimer=null,ebEmptySince=0,ebDayClock=0,ebCarPositions=new Map(),ebRadioState=new Map(),ebWorldSource=null;\nconst ebScheduleIdleNpc=()=>{if(idleNpcTimer||players.size===0||worldNeedsBootstrap||npcSnapshot.items.length!==0)return;idleNpcTimer=setTimeout(()=>{idleNpcTimer=null;if(players.size===0||worldNeedsBootstrap||npcSnapshot.items.length!==0)return;const nextRound=Math.max(1,Math.floor(round)+1),id='server:idle:'+Date.now();round=nextRound;const item={id,type:'pene',x:0,y:0,z:0,rx:0,ry:0,rz:0,hp:100,maxHp:100,walk:0,attack:false,protester:false,leap:false,leapPhase:0,fly:0,giant:false};npcSnapshot={seq:++seq,serverTime:Date.now(),round:nextRound,items:[item]};gameState={...gameState,seq:++seq,serverTime:Date.now(),round:nextRound,alive:1};ebEmptySince=0;io.emit('npc:snapshot',npcSnapshot);io.emit('round:state',nextRound);io.emit('game:state',gameState);io.emit('npc:revived',{round:nextRound,alive:1});log('NPC','Aparecio 1 NPC tras 15s con 0 vivos')},15000)};\nconst ebCancelIdleNpc=()=>{if(idleNpcTimer){clearTimeout(idleNpcTimer);idleNpcTimer=null}};\nconst ebRefreshCars=()=>{const old=Array.isArray(worldSnapshot?.items)?worldSnapshot.items.filter(x=>x?.type!=='car'):[];const cars=[...ebCarPositions].map(([index,c])=>({id:'car:'+index,type:'car',index,x:c.x,y:c.y,z:c.z,ry:c.ry||0,speed:c.speed||0,visible:true}));worldSnapshot={seq:++seq,serverTime:Date.now(),round,items:[...old,...cars]};return worldSnapshot};\nconst ebMergeWorld=(items)=>{const keep=(Array.isArray(worldSnapshot?.items)?worldSnapshot.items:[]).filter(x=>x?.type==='car');const incoming=(Array.isArray(items)?items:[]).filter(x=>x?.type!=='car'&&x?.id).slice(0,500);const by=new Map;for(const x of incoming)by.set(String(x.id),x);for(const x of worldSnapshot?.items||[])if(x?.type!=='car'&&x?.id&&!by.has(String(x.id)))by.set(String(x.id),x);worldSnapshot={seq:++seq,serverTime:Date.now(),round,items:[...by.values(),...keep]};return worldSnapshot};\nconst ebSetRadio=(index,radio)=>{if(!Number.isInteger(index)||index<0||!radio||!Number.isInteger(+radio.station))return null;const r={enabled:!!radio.enabled,station:Math.floor(+radio.station)};ebRadioState.set(index,r);carRadios.set(index,r);return r};\nlet npcSnapshot={seq:0,serverTime:0,round:0,items:[]},worldSnapshot=");
    x=x.replace(/const syncPack=\(\)=>\(\{round,players:/,"const syncPack=()=>{ebRefreshCars();return {round,players:");
    x=x.replace(/gameState,cars:publicCars\(\)\}\);/,'gameState,cars:publicCars()}};');
    x=x.replace(/s\.on\('player:state',d=>\{/ ,"s.on('player:state',d=>{if(d&&d.driving&&Number.isInteger(d.carIndex)&&d.carIndex>=0)ebCarPositions.set(d.carIndex,{x:num(d.carX),y:num(d.carY),z:num(d.carZ),ry:num(d.carRot),speed:num(d.carSpeed)});");
    x=x.replace(/s\.on\('car:radio:set',d=>\{[\s\S]*?\}\);/,"s.on('car:radio:set',d=>{const i=Math.floor(num(d?.index,-1)),st=Math.floor(num(d?.station,-1));if(i<0||st<0||carOwners.get(i)!==s.id)return;const r=ebSetRadio(i,{enabled:!!d?.enabled,station:st});io.emit('car:state',{index:i,owner:carOwners.get(i)||null,passenger:carPassengers.get(i)||null,radio:r});io.emit('car:radio:state',{index:i,radio:r})});");
    x=x.replace(/s\.emit\('room:welcome',\{id:s\.id,npcSource:s\.id===npcSource,\.\.\.syncPack\(\)\}\);/,"s.emit('room:welcome',{id:s.id,npcSource:false,canSpawnInitial:false,authoritativeJoin:true,npcJoinSnapshot:{round,alive:gameState.alive,seq:npcSnapshot.seq,serverTime:npcSnapshot.serverTime,items:npcSnapshot.items},...syncPack(),radioState:[...ebRadioState].map(([index,radio])=>({index,radio}))});");
    x=x.replace(/s\.on\('room:join',d=>\{p\.name=clean\(d\?\.name\);p\.round=round;s\.emit\('room:sync',syncPack\(\)\)\}\);/,"s.on('room:join',d=>{p.name=clean(d?.name);p.round=round;s.emit('room:sync',{...syncPack(),npcSource:false,authoritativeJoin:true,npcJoinSnapshot:{round,alive:gameState.alive,seq:npcSnapshot.seq,serverTime:npcSnapshot.serverTime,items:npcSnapshot.items},radioState:[...ebRadioState].map(([index,radio])=>({index,radio}))});s.emit('world:state',worldSnapshot);});");
    x += "\nsetInterval(()=>{if(players.size===0){ebCancelIdleNpc();ebEmptySince=0;return}if(npcSnapshot.items.length===0&&gameState.alive===0&&!worldNeedsBootstrap){if(!ebEmptySince)ebEmptySince=Date.now();if(Date.now()-ebEmptySince>=15000)ebScheduleIdleNpc()}else{ebEmptySince=0;ebCancelIdleNpc()}ebRefreshCars();io.emit('world:snapshot',worldSnapshot);ebDayClock=((Date.now()/1000)%1200)/1200*24;worldTime=ebDayClock;io.emit('world:time',{time:ebDayClock,serverTime:Date.now()})},500);\nsetInterval(()=>{for(const [i,r] of ebRadioState)io.emit('car:radio:state',{index:i,radio:r})},1000);\n";
    x=x.replace(/io\.on\('connection',s=>\{/ ,"io.on('connection',s=>{if(!ebWorldSource)ebWorldSource=s.id;s.on('eb:world:state',d=>{if(ebWorldSource!==s.id)return;ebMergeWorld(d?.items);io.emit('world:snapshot',worldSnapshot)});");
    x=x.replace(/s\.on\('car:claim',idx=>\{/ ,"s.on('car:claim',idx=>{");
    return x;
  }
  if(typeof out==='string'&&/Salva a cornatan .*\.html$/.test(name)){
    const tag='<script src="/online-final26.js?v=3"></script>';
    return out.replace(/<\/body>/i,tag+'</body>');
  }
  return out;
};
require('./server.js');
